using System.Collections.Generic;

namespace UltimateTeam.Toolkit.Parameters
{
    public class Team : SearchParameterBase<uint>
    {
        public const uint Heidenheim1846 = 111235;
        public const uint Kaiserslautern = 29;
        public const uint Koln = 31;
        public const uint Nurnberg = 171;
        public const uint UnionBerlin = 1831;
        public const uint Mainz05 = 169;
        public const uint AalborgBK = 820;
        public const uint AalesundsFK = 1755;
        public const uint AarhusGF = 271;
        public const uint Aberdeen = 77;
        public const uint ACHorsens = 1446;
        public const uint AccringtonStanley = 110313;
        public const uint ADAlcorcon = 100831;
        public const uint Adanaspor = 110401;
        public const uint AdelaideUnited = 111393;
        public const uint ADODenHaag = 650;
        public const uint AFCWimbledon = 112259;
        public const uint AIK = 433;
        public const uint AJAuxerre = 57;
        public const uint Ajax = 245;
        public const uint AkhisarBelediyespor = 111340;
        public const uint AlAhli = 112387;
        public const uint AlBatin = 112990;
        public const uint AlFaisaly = 112389;
        public const uint AlFateh = 112390;
        public const uint AlHilal = 605;
        public const uint AlIttihad = 607;
        public const uint AlKhaleej = 112883;
        public const uint AlNassr = 112139;
        public const uint AlQadisiyah = 112391;
        public const uint AlRaed = 112392;
        public const uint AlShabab = 111674;
        public const uint AlTaawoun = 112393;
        public const uint AlWehda = 112408;
        public const uint Alanyaspor = 113142;
        public const uint AlbirexNiigata = 112906;
        public const uint AlianzaPetrolera = 112579;
        public const uint AmiensSC = 1816;
        public const uint AmkarPerm = 110234;
        public const uint AngersSCO = 1530;
        public const uint Antalyaspor = 741;
        public const uint ArkaGdynia = 111082;
        public const uint Arsenal = 1;
        public const uint ArsenaldeSarandi = 110394;
        public const uint ASMonacoFootballClubSA = 69;
        public const uint ASNancyLorraine = 1823;
        public const uint ASSaintEtienne = 1819;
        public const uint Ascoli = 1847;
        public const uint AstonVilla = 2;
        public const uint Atalanta = 39;
        public const uint AthleticClub = 448;
        public const uint AthleticClubAjaccio = 614;
        public const uint AtikerKonyaspor = 101033;
        public const uint AtleticoBucaramanga = 112992;
        public const uint AtleticodeRafaela = 110392;
        public const uint AtleticoHuila = 112528;
        public const uint AtleticoMadrid = 240;
        public const uint AtleticoNacional = 101100;
        public const uint AtleticoTucuman = 111708;
        public const uint AudaxItaliano = 101097;
        public const uint Avellino = 2038;
        public const uint AvispaFukuoka = 113186;
        public const uint AZ = 1906;
        public const uint Bari = 1848;
        public const uint Barnet = 135;
        public const uint Barnsley = 1932;
        public const uint Bayer04Leverkusen = 32;
        public const uint BelgranodeCordoba = 111022;
        public const uint Benevento = 112026;
        public const uint BesiktasJK = 327;
        public const uint BirminghamCity = 88;
        public const uint BKHacken = 711;
        public const uint BlackburnRovers = 3;
        public const uint Blackpool = 1926;
        public const uint BoavistaFC = 1898;
        public const uint BocaJuniors = 1877;
        public const uint BohemianFC = 305;
        public const uint Bologna = 189;
        public const uint BoltonWanderers = 4;
        public const uint BorussiaDortmund = 22;
        public const uint BorussiaMonchengladbach = 23;
        public const uint BourgenBressePeronnas01 = 110576;
        public const uint Bournemouth = 1943;
        public const uint BoyacaChicoFC = 112019;
        public const uint BradfordCity = 1804;
        public const uint BrayWanderers = 838;
        public const uint Brentford = 1925;
        public const uint Brescia = 190;
        public const uint BrightonHoveAlbion = 1808;
        public const uint BrisbaneRoar = 111395;
        public const uint BristolCity = 1919;
        public const uint BristolRovers = 1962;
        public const uint BrondbyIF = 269;
        public const uint BrukBetTermalicaNieciecza = 112510;
        public const uint BSCYoungBoys = 900;
        public const uint Burnley = 1796;
        public const uint Bursaspor = 742;
        public const uint BurtonAlbion = 15015;
        public const uint Bury = 1945;
        public const uint CAOsasuna = 479;
        public const uint CadizCF = 1968;
        public const uint Cagliari = 1842;
        public const uint CambridgeUnited = 1944;
        public const uint CardiffCity = 1961;
        public const uint CarlisleUnited = 1480;
        public const uint Carpi = 112409;
        public const uint CaykurRizespor = 101037;
        public const uint CDAntofagasta = 112533;
        public const uint CDCobresal = 110978;
        public const uint CDEvertondeVinadelMar = 112584;
        public const uint CDHuachipato = 111327;
        public const uint CDLeganes = 100888;
        public const uint CDLugo = 110831;
        public const uint CDMirandes = 110069;
        public const uint CDNacional = 1891;
        public const uint CDNumancia = 477;
        public const uint CDOHiggins = 112116;
        public const uint CDPalestino = 111328;
        public const uint CDTenerife = 260;
        public const uint CDUniversidaddeConcepcion = 112534;
        public const uint Celtic = 78;
        public const uint CentralCoastMariners = 111396;
        public const uint Cesena = 110915;
        public const uint CFOsBelenenses = 1889;
        public const uint CFReus = 110854;
        public const uint ChamoisNiortaisFootballClub = 1813;
        public const uint CharltonAthletic = 89;
        public const uint Chaves = 518;
        public const uint Chelsea = 5;
        public const uint CheltenhamTown = 1936;
        public const uint Chesterfield = 1924;
        public const uint Chiavari = 113147;
        public const uint ChicagoFireSoccerClub = 693;
        public const uint ChievoVerona = 192;
        public const uint Cittadella = 111993;
        public const uint ClermontFoot63 = 1815;
        public const uint ClubAmerica = 1879;
        public const uint ClubAtlas = 101114;
        public const uint ClubAtleticoAldosivi = 111707;
        public const uint ClubAtleticoBanfield = 110404;
        public const uint ClubAtleticoHuracan = 111711;
        public const uint ClubAtleticoLanus = 110395;
        public const uint ClubAtleticoSarmiento = 112713;
        public const uint ClubAtleticoTalleres = 112670;
        public const uint ClubAtleticoTemperley = 112904;
        public const uint ClubBruggeKV = 231;
        public const uint ClubDeportesTemuco = 112709;
        public const uint ClubLeon = 110781;
        public const uint ClubNecaxa = 101121;
        public const uint ClubOlimpo = 110398;
        public const uint ClubTijuana = 111678;
        public const uint ColchesterUnited = 1935;
        public const uint ColoColo = 110980;
        public const uint ColondeSantaFe = 110406;
        public const uint ColoradoRapids = 694;
        public const uint ColumbusCrewSC = 687;
        public const uint CordobaCF = 1867;
        public const uint CorkCity = 422;
        public const uint CorporacionClubDeportivoTulua = 112934;
        public const uint CoventryCity = 1800;
        public const uint Cracovia = 110747;
        public const uint CrawleyTown = 110890;
        public const uint CreweAlexandra = 121;
        public const uint Crotone = 110734;
        public const uint CruzAzul = 1878;
        public const uint CrystalPalace = 1799;
        public const uint CSMaritimo = 1893;
        public const uint CSKAMoscow = 315;
        public const uint DAlaves = 463;
        public const uint DCUnited = 688;
        public const uint DefensayJusticia = 111710;
        public const uint DeportesIquique = 112531;
        public const uint DeportesTolima = 111722;
        public const uint DeportivoCali = 101102;
        public const uint DeportivoPasto = 111723;
        public const uint DeportivoToluca = 1882;
        public const uint DerbyCounty = 91;
        public const uint DerryCity = 445;
        public const uint DijonFCO = 110569;
        public const uint DjurgardensIF = 710;
        public const uint DoncasterRovers = 142;
        public const uint DSCArminiaBielefeld = 159;
        public const uint Dundalk = 837;
        public const uint DundeeFC = 180;
        public const uint EintrachtBraunschweig = 110500;
        public const uint EintrachtFrankfurt = 1824;
        public const uint ElcheCF = 468;
        public const uint Empoli = 1746;
        public const uint EnAvantdeGuingamp = 62;
        public const uint EnvigadoFC = 112526;
        public const uint EsbjergfB = 1445;
        public const uint ESTACTroyes = 294;
        public const uint EstorilPraia = 10020;
        public const uint EstudiantesdeLaPlata = 101083;
        public const uint EttifaqFC = 112096;
        public const uint Everton = 7;
        public const uint Excelsior = 1971;
        public const uint ExeterCity = 143;
        public const uint FSantaMariadaFeira = 10019;
        public const uint FCTokyo = 101150;
        public const uint FalkenbergsFF = 112169;
        public const uint FCAdmiraWackerModling = 111821;
        public const uint FCAnzhiMakhachkala = 100766;
        public const uint FCArouca = 112513;
        public const uint FCArsenalTula = 110756;
        public const uint FCAugsburg = 100409;
        public const uint FCBarcelona = 241;
        public const uint FCBasel = 896;
        public const uint FCBayernMunchen = 21;
        public const uint FCDallas = 695;
        public const uint FCErzgebirgeAue = 506;
        public const uint FCGirondinsdeBordeaux = 59;
        public const uint FCGroningen = 1915;
        public const uint FCIngolstadt04 = 111239;
        public const uint FCKobenhavn = 819;
        public const uint FCKrasnodar = 112218;
        public const uint FCKrylyaSovetovSamara = 100764;
        public const uint FCLausanneSport = 1862;
        public const uint FCLorient = 217;
        public const uint FCLugano = 10032;
        public const uint FCLuzern = 897;
        public const uint FCMidtjylland = 1516;
        public const uint FCNantes = 71;
        public const uint FCNordsjaelland = 1788;
        public const uint FCOrenburg = 112261;
        public const uint FCPacosdeFerreira = 1892;
        public const uint FCPorto = 236;
        public const uint FCRedBullSalzburg = 191;
        public const uint FCRostov = 110231;
        public const uint FCSchalke04 = 34;
        public const uint FCSeoul = 982;
        public const uint FCSion = 110770;
        public const uint FCSochauxMontbeliard = 226;
        public const uint FCStGallen = 898;
        public const uint FCStPauliHamburg = 110329;
        public const uint FCThun = 1715;
        public const uint FCTomTomsk = 110233;
        public const uint FCTwente = 1908;
        public const uint FCUfa = 110822;
        public const uint FCUral = 111264;
        public const uint FCUtrecht = 1903;
        public const uint FCVaduz = 286;
        public const uint FCWurzburgerKickers = 110197;
        public const uint FenerbahceSK = 326;
        public const uint Ferrara = 112791;
        public const uint Feyenoord = 246;
        public const uint FinnHarps = 111131;
        public const uint Fiorentina = 110374;
        public const uint FKAustriaWien = 256;
        public const uint FKBodoGlimt = 918;
        public const uint FKHaugesund = 1463;
        public const uint FleetwoodTown = 112260;
        public const uint FootballClubdeMetz = 68;
        public const uint FortalezaCEIF = 112834;
        public const uint FortunaDusseldorf = 110636;
        public const uint Frosinone = 111657;
        public const uint Fulham = 144;
        public const uint GalatasaraySK = 325;
        public const uint GalwayUnited = 1571;
        public const uint GambaOsaka = 112093;
        public const uint GazelecFootballClubAjaccio = 110316;
        public const uint Gaziantepspor = 101024;
        public const uint GefleIF = 111277;
        public const uint GenclerbirligiSK = 101025;
        public const uint Genoa = 110556;
        public const uint GetafeCF = 1860;
        public const uint GIFSundsvall = 1596;
        public const uint Gillingham = 1802;
        public const uint GimnasiayEsgrimaLaPlata = 101084;
        public const uint GironaFC = 110062;
        public const uint GoAheadEagles = 100632;
        public const uint GodoyCruz = 111706;
        public const uint GornikLeczna = 110565;
        public const uint GranadaCF = 110832;
        public const uint GrasshopperClubZurich = 322;
        public const uint GrimsbyTown = 92;
        public const uint Guadalajara = 1880;
        public const uint GwangJuFC = 112258;
        public const uint HamburgerSV = 28;
        public const uint HamiltonAcademicalFC = 184;
        public const uint HammarbyIF = 708;
        public const uint Hannover96 = 485;
        public const uint HartlepoolUnited = 1941;
        public const uint HavreAthleticClub = 1738;
        public const uint HeartofMidlothian = 80;
        public const uint HellasVerona = 206;
        public const uint HelsingborgsIF = 432;
        public const uint HeraclesAlmelo = 100634;
        public const uint HerthaBerlin = 166;
        public const uint HJKHelsinki = 100325;
        public const uint HoustonDynamo = 698;
        public const uint HuddersfieldTown = 1939;
        public const uint HullCity = 1952;
        public const uint IFElfsborg = 700;
        public const uint IFKGoteborg = 319;
        public const uint IFKNorrkoping = 702;
        public const uint IKStart = 1524;
        public const uint IncheonUnitedFC = 110765;
        public const uint Independiente = 110093;
        public const uint IndependienteMedellin = 101103;
        public const uint IndependienteSantaFe = 101104;
        public const uint Inter = 44;
        public const uint InvernessCaledonianThistle = 620;
        public const uint IpswichTown = 94;
        public const uint JagielloniaBialystok = 110745;
        public const uint JaguaresdeChiapas = 112679;
        public const uint JaguaresFutbolClub = 112903;
        public const uint JejuUnitedFC = 1478;
        public const uint JeonbukHyundaiMotors = 1477;
        public const uint JeonnamDragons = 1475;
        public const uint JonkopingsSodraIF = 112130;
        public const uint JubiloIwata = 101144;
        public const uint JuniorFC = 101101;
        public const uint Juventus = 45;
        public const uint KAAGent = 674;
        public const uint KaizerChiefs = 110929;
        public const uint KalmarFF = 1439;
        public const uint KardemirKarabukspor = 112122;
        public const uint KarlsruherSC = 1832;
        public const uint KASEupen = 2013;
        public const uint KashimaAntlers = 101147;
        public const uint KashiwaReysol = 101145;
        public const uint KasimpasaSK = 111339;
        public const uint KawasakiFrontale = 111730;
        public const uint Kayserispor = 101020;
        public const uint Kilmarnock = 82;
        public const uint KoronaKielce = 111083;
        public const uint KRCGenk = 673;
        public const uint KVKortrijk = 100081;
        public const uint KVMechelen = 110724;
        public const uint KVOostende = 682;
        public const uint KVCWesterlo = 681;
        public const uint LaEquidad = 112523;
        public const uint LAGalaxy = 697;
        public const uint LaSpezia = 110741;
        public const uint Latina = 112487;
        public const uint Lazio = 46;
        public const uint LechPoznan = 873;
        public const uint LechiaGdansk = 111091;
        public const uint LeedsUnited = 8;
        public const uint Legends = 112658;
        public const uint LegiaWarszawa = 1871;
        public const uint LeicesterCity = 95;
        public const uint LevanteUD = 1853;
        public const uint LeytonOrient = 1958;
        public const uint LillestromSK = 299;
        public const uint Liniers = 101088;
        public const uint Liverpool = 9;
        public const uint LokomotivMoscow = 100765;
        public const uint LongfordTown = 1586;
        public const uint LOSCLille = 65;
        public const uint LutonTown = 1923;
        public const uint LyngbyBK = 15001;
        public const uint MalagaCF = 573;
        public const uint MalmoFF = 320;
        public const uint ManchesterCity = 10;
        public const uint ManchesterUnited = 11;
        public const uint MansfieldTown = 1940;
        public const uint MedipolBasaksehirFK = 101014;
        public const uint MelbourneCity = 112224;
        public const uint MelbourneVictory = 111397;
        public const uint Middlesbrough = 12;
        public const uint Milan = 47;
        public const uint MillonariosFC = 101105;
        public const uint Millwall = 97;
        public const uint MiltonKeynesDons = 1798;
        public const uint MoldeFK = 417;
        public const uint MonarcasMorelia = 1028;
        public const uint Monterrey = 1032;
        public const uint MontpellierHeraultSC = 70;
        public const uint MontrealImpact = 111139;
        public const uint Morecambe = 357;
        public const uint MoreirenseFC = 1900;
        public const uint Motherwell = 83;
        public const uint NEC = 1910;
        public const uint NagoyaGrampus = 112092;
        public const uint Napoli = 48;
        public const uint Nastic = 15019;
        public const uint NewEnglandRevolution = 691;
        public const uint NewYorkCityFootballClub = 112828;
        public const uint NewYorkRedBulls = 689;
        public const uint NewcastleJets = 111398;
        public const uint NewcastleUnited = 13;
        public const uint NewellsOldBoys = 110396;
        public const uint NewportCounty = 112254;
        public const uint NimesOlympique = 224;
        public const uint NorthamptonTown = 1930;
        public const uint NorwichCity = 1792;
        public const uint NottinghamForest = 14;
        public const uint NottsCounty = 1937;
        public const uint Novara = 112225;
        public const uint OddsBK = 1456;
        public const uint OdenseBoldklub = 272;
        public const uint OGCNice = 72;
        public const uint OldhamAthletic = 1920;
        public const uint OlympiacosCFP = 280;
        public const uint OlympiquedeMarseille = 219;
        public const uint OlympiqueLyonnais = 66;
        public const uint OmiyaArdija = 112345;
        public const uint OnceCaldas = 101106;
        public const uint OrebroSK = 705;
        public const uint OrlandoCitySoccerClub = 112606;
        public const uint OrlandoPirates = 110930;
        public const uint Osmanlispor = 112958;
        public const uint OstersundsFK = 113173;
        public const uint OxfordUnited = 1951;
        public const uint Pachuca = 110147;
        public const uint Palermo = 1843;
        public const uint PanathinaikosFC = 1884;
        public const uint PAOK = 393;
        public const uint ParisSaintGermain = 73;
        public const uint PartickThistleFC = 1754;
        public const uint PatriotasBoyacaFC = 112527;
        public const uint Patronato = 110581;
        public const uint PECZwolle = 1914;
        public const uint PerthGlory = 111399;
        public const uint Perugia = 199;
        public const uint Pescara = 200;
        public const uint PeterboroughUnited = 1938;
        public const uint PhiladelphiaUnion = 112134;
        public const uint PiastGliwice = 111086;
        public const uint Pisa = 110738;
        public const uint PlymouthArgyle = 1929;
        public const uint PogonSzczecin = 110746;
        public const uint PohangSteelers = 1474;
        public const uint PortVale = 1928;
        public const uint PortlandTimbers = 111140;
        public const uint Portsmouth = 1790;
        public const uint PrestonNorthEnd = 1801;
        public const uint PSV = 247;
        public const uint Puebla = 110152;
        public const uint QueensParkRangers = 15;
        public const uint Queretaro = 110150;
        public const uint QuilmesAtleticoClub = 110554;
        public const uint ROviedo = 110827;
        public const uint RSporting = 459;
        public const uint RValladolidCF = 462;
        public const uint RZaragoza = 244;
        public const uint RacingClub = 101085;
        public const uint RacingClubdeLens = 64;
        public const uint RandersFC = 1786;
        public const uint RangersFC = 86;
        public const uint RayoVallecano = 480;
        public const uint RBLeipzig = 112172;
        public const uint RCCelta = 450;
        public const uint RCDeportivo = 242;
        public const uint RCStrasbourgAlsace = 76;
        public const uint RCDEspanyol = 452;
        public const uint RCDMallorca = 453;
        public const uint Reading = 1793;
        public const uint RealBetis = 449;
        public const uint RealMadrid = 243;
        public const uint RealSaltLake = 111065;
        public const uint RealSociedad = 457;
        public const uint RedStarFC = 111273;
        public const uint RioAveFC = 744;
        public const uint RionegroAguilas = 112578;
        public const uint RiverPlate = 1876;
        public const uint Rochdale = 1955;
        public const uint RodaJCKerkrade = 1902;
        public const uint Roma = 52;
        public const uint RosarioCentral = 110580;
        public const uint RosenborgBK = 298;
        public const uint RossCountyFC = 631;
        public const uint RotherhamUnited = 1797;
        public const uint RoyalExcelMouscron = 111560;
        public const uint RSCAnderlecht = 229;
        public const uint RubinKazan = 110227;
        public const uint RuchChorzow = 874;
        public const uint SaganTosu = 113160;
        public const uint Salerno = 110373;
        public const uint Sampdoria = 1837;
        public const uint SanJoseEarthquakes = 111928;
        public const uint SanLorenzodeAlmagro = 1013;
        public const uint SanLuisdeQuillota = 112668;
        public const uint SanMartin = 111713;
        public const uint SanfrecceHiroshima = 113157;
        public const uint SangjuSangmuFC = 2055;
        public const uint SantiagoWanderers = 110976;
        public const uint SantosLaguna = 110144;
        public const uint Sarpsborg08FF = 112199;
        public const uint Sassuolo = 111974;
        public const uint SCBraga = 1896;
        public const uint SCHeerenveen = 1913;
        public const uint SCRAltach = 15009;
        public const uint ScunthorpeUnited = 1949;
        public const uint SDEibar = 467;
        public const uint SDHuesca = 110839;
        public const uint SeattleSoundersFC = 111144;
        public const uint SeongnamFC = 981;
        public const uint SevillaAtletico = 110714;
        public const uint SevillaFC = 481;
        public const uint SGDynamoDresden = 503;
        public const uint ShakhtarDonetsk = 101059;
        public const uint ShamrockRovers = 306;
        public const uint SheffieldUnited = 1794;
        public const uint SheffieldWednesday = 1807;
        public const uint ShonanBellmare = 113161;
        public const uint Shrewsbury = 127;
        public const uint SilkeborgIF = 270;
        public const uint SintTruidenseVV = 680;
        public const uint SKBrann = 919;
        public const uint SKRapidWien = 254;
        public const uint SKSturmGraz = 209;
        public const uint SKNStPolten = 112075;
        public const uint SLBenfica = 234;
        public const uint SlaskWroclaw = 111092;
        public const uint SligoRovers = 563;
        public const uint SogndalFotball = 1465;
        public const uint SonderjyskE = 1447;
        public const uint Southampton = 17;
        public const uint SouthendUnited = 1954;
        public const uint SpartaRotterdam = 100646;
        public const uint SpartakMoscow = 100767;
        public const uint SportClubFreiburg = 25;
        public const uint SportingCharleroi = 670;
        public const uint SportingClubdeBastia = 58;
        public const uint SportingCP = 237;
        public const uint SportingKansasCity = 696;
        public const uint SportingLokeren = 2007;
        public const uint SpVggGreutherFuerth = 165;
        public const uint StJohnstoneFC = 100804;
        public const uint StPatricksAthletic = 423;
        public const uint StabaekFotball = 917;
        public const uint StadeBrestois29 = 378;
        public const uint StadedeReims = 379;
        public const uint StadeLavalloisMayenneFC = 1814;
        public const uint StadeMalherbeCaen = 210;
        public const uint StadeRennaisFC = 74;
        public const uint StandarddeLiege = 232;
        public const uint Stevenage = 361;
        public const uint StokeCity = 1806;
        public const uint StromsgodsetIF = 922;
        public const uint Sunderland = 106;
        public const uint SuwonFC = 112558;
        public const uint SuwonSamsungBluewings = 983;
        public const uint SVDarmstadt98 = 110502;
        public const uint SVGuntamaticRied = 780;
        public const uint SVMattersburg = 1785;
        public const uint SVSandhausen = 110178;
        public const uint SVWerderBremen = 38;
        public const uint SVZulteWaregem = 15005;
        public const uint SwanseaCity = 1960;
        public const uint SwindonTown = 1934;
        public const uint SydneyFC = 111400;
        public const uint TerekGrozny = 110109;
        public const uint Terni = 570;
        public const uint TiburonesRojosdeVeracruz = 110145;
        public const uint TigresUANL = 1970;
        public const uint Tondela = 112516;
        public const uint Torino = 54;
        public const uint TorontoFC = 111651;
        public const uint TottenhamHotspur = 18;
        public const uint ToulouseFootballClub = 1809;
        public const uint ToursFootballClub = 110326;
        public const uint Trabzonspor = 436;
        public const uint Trapani = 112410;
        public const uint TromsoIL = 418;
        public const uint TSG1899Hoffenheim = 10029;
        public const uint TSV1860Munchen = 33;
        public const uint UNAM = 1881;
        public const uint UCAMMurciaCF = 113216;
        public const uint UDAlmeria = 1861;
        public const uint UDLasPalmas = 472;
        public const uint Udinese = 55;
        public const uint UlsanHyundaiHorangi = 1473;
        public const uint UniondeSantaFe = 111716;
        public const uint UnionEspanola = 110977;
        public const uint UniversidadCatolica = 110975;
        public const uint UniversidaddeChile = 15029;
        public const uint UrawaRedDiamonds = 111575;
        public const uint USOrleansLoiretFootball = 112276;
        public const uint ValenciaCF = 461;
        public const uint ValenciennesFC = 110456;
        public const uint ValerengaFotball = 920;
        public const uint VancouverWhitecapsFC = 101112;
        public const uint VegaltaSendai = 112836;
        public const uint VentforetKofu = 113162;
        public const uint Vercelli = 112398;
        public const uint VfBStuttgart = 36;
        public const uint VfLBochum1848 = 160;
        public const uint VfLWolfsburg = 175;
        public const uint ViborgFF = 1443;
        public const uint Vicenza = 112954;
        public const uint Victoria = 111715;
        public const uint VikingFK = 300;
        public const uint VillarrealCF = 483;
        public const uint VisselKobe = 101146;
        public const uint Vitesse = 1909;
        public const uint VitoriaGuimaraes = 1887;
        public const uint VitoriaSetubal = 665;
        public const uint WaaslandBeveren = 110913;
        public const uint Walsall = 1803;
        public const uint Watford = 1795;
        public const uint WellingtonPhoenix = 111766;
        public const uint WestBromwichAlbion = 109;
        public const uint WestHamUnited = 19;
        public const uint WesternSydneyWanderers = 112427;
        public const uint WexfordYouths = 111968;
        public const uint WiganAthletic = 1917;
        public const uint WillemII = 1907;
        public const uint WislaKrakow = 1873;
        public const uint WislaPlock = 1569;
        public const uint WolfsbergerAC = 111822;
        public const uint WolverhamptonWanderers = 110;
        public const uint WycombeWanderers = 1933;
        public const uint YeovilTown = 346;
        public const uint YokohamaFMarinos = 101151;
        public const uint ZaglebieLubin = 110749;
        public const uint ZenitStPetersburg = 100769;

        private Team(string description, uint value, uint league)
        {
            Description = description;
            Value = value;
            Parent = league;
        }

        public static IEnumerable<Team> GetAll()
        {
            yield return new Team("FC Heidenheim 1846", Heidenheim1846, League.Bundesliga2);
            yield return new Team("FC Kaiserslautern", Kaiserslautern, League.Bundesliga2);
            yield return new Team("FC Koln", Koln, League.Bundesliga);
            yield return new Team("FC Nurnberg", Nurnberg, League.Bundesliga2);
            yield return new Team("FC Union Berlin", UnionBerlin, League.Bundesliga2);
            yield return new Team("FSV Mainz 05", Mainz05, League.Bundesliga);
            yield return new Team("Aalborg BK", AalborgBK, League.AlkaSuperliga);
            yield return new Team("Aalesunds FK", AalesundsFK, League.Tippeligaen);
            yield return new Team("Aarhus GF", AarhusGF, League.AlkaSuperliga);
            yield return new Team("Aberdeen", Aberdeen, League.ScottishPremiership);
            yield return new Team("AC Horsens", ACHorsens, League.PremierLeague);
            yield return new Team("Accrington Stanley", AccringtonStanley, League.EFLLeagueTwo);
            yield return new Team("AD Alcorcon", ADAlcorcon, League.LaLiga123);
            yield return new Team("Adanaspor", Adanaspor, League.SuperLig);
            yield return new Team("Adelaide United", AdelaideUnited, League.HyundaiALeague);
            yield return new Team("ADO Den Haag", ADODenHaag, League.Eredivisie);
            yield return new Team("AFC Wimbledon", AFCWimbledon, League.EFLLeagueOne);
            yield return new Team("AIK", AIK, League.Allsvenskan);
            yield return new Team("AJ Auxerre", AJAuxerre, League.DominosLigue2);
            yield return new Team("Ajax", Ajax, League.Eredivisie);
            yield return new Team("Akhisar Belediyespor", AkhisarBelediyespor, League.SuperLig);
            yield return new Team("Al Ahli", AlAhli, League.DawryJameel);
            yield return new Team("Al Batin", AlBatin, League.DawryJameel);
            yield return new Team("Al Faisaly", AlFaisaly, League.DawryJameel);
            yield return new Team("Al Fateh", AlFateh, League.DawryJameel);
            yield return new Team("Al Hilal", AlHilal, League.DawryJameel);
            yield return new Team("Al Ittihad", AlIttihad, League.DawryJameel);
            yield return new Team("Al Khaleej", AlKhaleej, League.DawryJameel);
            yield return new Team("Al Nassr", AlNassr, League.DawryJameel);
            yield return new Team("Al Qadisiyah", AlQadisiyah, League.DawryJameel);
            yield return new Team("Al Raed", AlRaed, League.DawryJameel);
            yield return new Team("Al Shabab", AlShabab, League.DawryJameel);
            yield return new Team("Al Taawoun", AlTaawoun, League.DawryJameel);
            yield return new Team("Al Wehda", AlWehda, League.DawryJameel);
            yield return new Team("Alanyaspor", Alanyaspor, League.SuperLig);
            yield return new Team("Albirex Niigata", AlbirexNiigata, League.MeijiYasudaJ1League);
            yield return new Team("Alianza Petrolera", AlianzaPetrolera, League.LigaDimayor);
            yield return new Team("Amiens SC", AmiensSC, League.DominosLigue2);
            yield return new Team("Amkar Perm", AmkarPerm, League.RSL);
            yield return new Team("Angers SCO", AngersSCO, League.Ligue1);
            yield return new Team("Antalyaspor", Antalyaspor, League.SuperLig);
            yield return new Team("Arka Gdynia", ArkaGdynia, League.Ekstraklasa);
            yield return new Team("Arsenal", Arsenal, League.PremierLeague);
            yield return new Team("Arsenal de Sarandi", ArsenaldeSarandi, League.PrimeraDivision);
            yield return new Team("AS Monaco Football Club SA", ASMonacoFootballClubSA, League.Ligue1);
            yield return new Team("AS Nancy Lorraine", ASNancyLorraine, League.Ligue1);
            yield return new Team("AS Saint-Etienne", ASSaintEtienne, League.Ligue1);
            yield return new Team("Ascoli", Ascoli, League.CalcioB);
            yield return new Team("Aston Villa", AstonVilla, League.EFLChampionship);
            yield return new Team("Atalanta", Atalanta, League.CalcioA);
            yield return new Team("Athletic Club", AthleticClub, League.LaLigaSantander);
            yield return new Team("Athletic Club Ajaccio", AthleticClubAjaccio, League.DominosLigue2);
            yield return new Team("Atiker Konyaspor", AtikerKonyaspor, League.SuperLig);
            yield return new Team("Atletico Bucaramanga", AtleticoBucaramanga, League.LigaDimayor);
            yield return new Team("Atletico de Rafaela", AtleticodeRafaela, League.PrimeraDivision);
            yield return new Team("Atletico Huila", AtleticoHuila, League.LigaDimayor);
            yield return new Team("Atletico Madrid", AtleticoMadrid, League.LaLigaSantander);
            yield return new Team("Atletico Nacional", AtleticoNacional, League.LigaDimayor);
            yield return new Team("Atletico Tucuman", AtleticoTucuman, League.PrimeraDivision);
            yield return new Team("Audax Italiano", AudaxItaliano, League.CampScotiabank);
            yield return new Team("Avellino", Avellino, League.CalcioB);
            yield return new Team("Avispa Fukuoka", AvispaFukuoka, League.MeijiYasudaJ1League);
            yield return new Team("AZ", AZ, League.Eredivisie);
            yield return new Team("Bari", Bari, League.CalcioB);
            yield return new Team("Barnet", Barnet, League.EFLLeagueTwo);
            yield return new Team("Barnsley", Barnsley, League.EFLChampionship);
            yield return new Team("Bayer 04 Leverkusen", Bayer04Leverkusen, League.Bundesliga);
            yield return new Team("Belgrano de Cordoba", BelgranodeCordoba, League.PrimeraDivision);
            yield return new Team("Benevento", Benevento, League.CalcioB);
            yield return new Team("Besiktas JK", BesiktasJK, League.SuperLig);
            yield return new Team("Birmingham City", BirminghamCity, League.EFLChampionship);
            yield return new Team("BK Hacken", BKHacken, League.Allsvenskan);
            yield return new Team("Blackburn Rovers", BlackburnRovers, League.EFLChampionship);
            yield return new Team("Blackpool", Blackpool, League.EFLLeagueTwo);
            yield return new Team("Boavista FC", BoavistaFC, League.LigaNOS);
            yield return new Team("Boca Juniors", BocaJuniors, League.PrimeraDivision);
            yield return new Team("Bohemian FC", BohemianFC, League.SSEAirtricityLeague);
            yield return new Team("Bologna", Bologna, League.CalcioA);
            yield return new Team("Bolton Wanderers", BoltonWanderers, League.EFLLeagueOne);
            yield return new Team("Borussia Dortmund", BorussiaDortmund, League.Bundesliga);
            yield return new Team("Borussia Monchengladbach", BorussiaMonchengladbach, League.Bundesliga);
            yield return new Team("Bourg en Bresse Peronnas 01", BourgenBressePeronnas01, League.DominosLigue2);
            yield return new Team("Bournemouth", Bournemouth, League.PremierLeague);
            yield return new Team("Boyaca Chico FC", BoyacaChicoFC, League.LigaDimayor);
            yield return new Team("Bradford City", BradfordCity, League.EFLLeagueOne);
            yield return new Team("Bray Wanderers", BrayWanderers, League.SSEAirtricityLeague);
            yield return new Team("Brentford", Brentford, League.EFLChampionship);
            yield return new Team("Brescia", Brescia, League.CalcioB);
            yield return new Team("Brighton & Hove Albion", BrightonHoveAlbion, League.EFLChampionship);
            yield return new Team("Brisbane Roar", BrisbaneRoar, League.HyundaiALeague);
            yield return new Team("Bristol City", BristolCity, League.EFLChampionship);
            yield return new Team("Bristol Rovers", BristolRovers, League.EFLLeagueOne);
            yield return new Team("Brondby IF", BrondbyIF, League.AlkaSuperliga);
            yield return new Team("Bruk-Bet Termalica Nieciecza", BrukBetTermalicaNieciecza, League.Ekstraklasa);
            yield return new Team("BSC Young Boys", BSCYoungBoys, League.RSL);
            yield return new Team("Burnley", Burnley, League.PremierLeague);
            yield return new Team("Bursaspor", Bursaspor, League.SuperLig);
            yield return new Team("Burton Albion", BurtonAlbion, League.EFLChampionship);
            yield return new Team("Bury", Bury, League.EFLLeagueOne);
            yield return new Team("CA Osasuna", CAOsasuna, League.LaLigaSantander);
            yield return new Team("Cadiz CF", CadizCF, League.LaLiga123);
            yield return new Team("Cagliari", Cagliari, League.CalcioA);
            yield return new Team("Cambridge United", CambridgeUnited, League.EFLLeagueTwo);
            yield return new Team("Cardiff City", CardiffCity, League.EFLChampionship);
            yield return new Team("Carlisle United", CarlisleUnited, League.EFLLeagueTwo);
            yield return new Team("Carpi", Carpi, League.CalcioB);
            yield return new Team("Caykur Rizespor", CaykurRizespor, League.SuperLig);
            yield return new Team("CD Antofagasta", CDAntofagasta, League.CampScotiabank);
            yield return new Team("CD Cobresal", CDCobresal, League.CampScotiabank);
            yield return new Team("CD Everton de Vina del Mar", CDEvertondeVinadelMar, League.CampScotiabank);
            yield return new Team("CD Huachipato", CDHuachipato, League.CampScotiabank);
            yield return new Team("CD Leganes", CDLeganes, League.LaLigaSantander);
            yield return new Team("CD Lugo", CDLugo, League.LaLiga123);
            yield return new Team("CD Mirandes", CDMirandes, League.LaLiga123);
            yield return new Team("CD Nacional", CDNacional, League.LigaNOS);
            yield return new Team("CD Numancia", CDNumancia, League.LaLiga123);
            yield return new Team("CD O'Higgins", CDOHiggins, League.CampScotiabank);
            yield return new Team("CD Palestino", CDPalestino, League.CampScotiabank);
            yield return new Team("CD Tenerife", CDTenerife, League.LaLiga123);
            yield return new Team("CD Universidad de Concepcion", CDUniversidaddeConcepcion, League.CampScotiabank);
            yield return new Team("Celtic", Celtic, League.ScottishPremiership);
            yield return new Team("Central Coast Mariners", CentralCoastMariners, League.HyundaiALeague);
            yield return new Team("Cesena", Cesena, League.CalcioA);
            yield return new Team("CF Os Belenenses", CFOsBelenenses, League.LigaNOS);
            yield return new Team("CF Reus", CFReus, League.LaLiga123);
            yield return new Team("Chamois Niortais Football Club", ChamoisNiortaisFootballClub, League.DominosLigue2);
            yield return new Team("Charlton Athletic", CharltonAthletic, League.EFLLeagueOne);
            yield return new Team("Chaves", Chaves, League.LigaNOS);
            yield return new Team("Chelsea", Chelsea, League.PremierLeague);
            yield return new Team("Cheltenham Town", CheltenhamTown, League.EFLLeagueTwo);
            yield return new Team("Chesterfield", Chesterfield, League.EFLLeagueOne);
            yield return new Team("Chiavari", Chiavari, League.CalcioB);
            yield return new Team("Chicago Fire Soccer Club", ChicagoFireSoccerClub, League.MLS);
            yield return new Team("Chievo Verona", ChievoVerona, League.CalcioA);
            yield return new Team("Cittadella", Cittadella, League.CalcioB);
            yield return new Team("Clermont Foot 63", ClermontFoot63, League.DominosLigue2);
            yield return new Team("Club America", ClubAmerica, League.LIGABancomerMX);
            yield return new Team("Club Atlas", ClubAtlas, League.LIGABancomerMX);
            yield return new Team("Club Atletico Aldosivi", ClubAtleticoAldosivi, League.PrimeraDivision);
            yield return new Team("Club Atletico Banfield", ClubAtleticoBanfield, League.PrimeraDivision);
            yield return new Team("Club Atletico Huracan", ClubAtleticoHuracan, League.PrimeraDivision);
            yield return new Team("Club Atletico Lanus", ClubAtleticoLanus, League.PrimeraDivision);
            yield return new Team("Club Atletico Sarmiento", ClubAtleticoSarmiento, League.PrimeraDivision);
            yield return new Team("Club Atletico Talleres", ClubAtleticoTalleres, League.PrimeraDivision);
            yield return new Team("Club Atletico Temperley", ClubAtleticoTemperley, League.PrimeraDivision);
            yield return new Team("Club Brugge KV", ClubBruggeKV, League.ProLeague);
            yield return new Team("Club Deportes Temuco", ClubDeportesTemuco, League.CampScotiabank);
            yield return new Team("Club Leon", ClubLeon, League.LIGABancomerMX);
            yield return new Team("Club Necaxa", ClubNecaxa, League.LIGABancomerMX);
            yield return new Team("Club Olimpo", ClubOlimpo, League.PrimeraDivision);
            yield return new Team("Club Tijuana", ClubTijuana, League.LIGABancomerMX);
            yield return new Team("Colchester United", ColchesterUnited, League.EFLLeagueTwo);
            yield return new Team("Colo-Colo", ColoColo, League.CampScotiabank);
            yield return new Team("Colon de Santa Fe", ColondeSantaFe, League.PrimeraDivision);
            yield return new Team("Colorado Rapids", ColoradoRapids, League.MLS);
            yield return new Team("Columbus Crew SC", ColumbusCrewSC, League.MLS);
            yield return new Team("Cordoba CF", CordobaCF, League.LaLiga123);
            yield return new Team("Cork City", CorkCity, League.SSEAirtricityLeague);
            yield return new Team("Corporacion Club Deportivo Tulua", CorporacionClubDeportivoTulua, League.LigaDimayor);
            yield return new Team("Coventry City", CoventryCity, League.EFLLeagueOne);
            yield return new Team("Cracovia", Cracovia, League.Ekstraklasa);
            yield return new Team("Crawley Town", CrawleyTown, League.EFLLeagueTwo);
            yield return new Team("Crewe Alexandra", CreweAlexandra, League.EFLLeagueTwo);
            yield return new Team("Crotone", Crotone, League.CalcioA);
            yield return new Team("Cruz Azul", CruzAzul, League.LIGABancomerMX);
            yield return new Team("Crystal Palace", CrystalPalace, League.PremierLeague);
            yield return new Team("CS Maritimo", CSMaritimo, League.LigaNOS);
            yield return new Team("CSKA Moscow", CSKAMoscow, League.RSL);
            yield return new Team("D. Alaves", DAlaves, League.LaLigaSantander);
            yield return new Team("D.C. United", DCUnited, League.MLS);
            yield return new Team("Defensa y Justicia", DefensayJusticia, League.PrimeraDivision);
            yield return new Team("Deportes Iquique", DeportesIquique, League.CampScotiabank);
            yield return new Team("Deportes Tolima", DeportesTolima, League.LigaDimayor);
            yield return new Team("Deportivo Cali", DeportivoCali, League.LigaDimayor);
            yield return new Team("Deportivo Pasto", DeportivoPasto, League.LigaDimayor);
            yield return new Team("Deportivo Toluca", DeportivoToluca, League.LIGABancomerMX);
            yield return new Team("Derby County", DerbyCounty, League.EFLChampionship);
            yield return new Team("Derry City", DerryCity, League.SSEAirtricityLeague);
            yield return new Team("Dijon FCO", DijonFCO, League.Ligue1);
            yield return new Team("Djurgardens IF", DjurgardensIF, League.Allsvenskan);
            yield return new Team("Doncaster Rovers", DoncasterRovers, League.EFLLeagueTwo);
            yield return new Team("DSC Arminia Bielefeld", DSCArminiaBielefeld, League.Bundesliga2);
            yield return new Team("Dundalk", Dundalk, League.SSEAirtricityLeague);
            yield return new Team("Dundee FC", DundeeFC, League.ScottishPremiership);
            yield return new Team("Eintracht Braunschweig", EintrachtBraunschweig, League.Bundesliga2);
            yield return new Team("Eintracht Frankfurt", EintrachtFrankfurt, League.Bundesliga);
            yield return new Team("Elche CF", ElcheCF, League.LaLiga123);
            yield return new Team("Empoli", Empoli, League.CalcioA);
            yield return new Team("En Avant de Guingamp", EnAvantdeGuingamp, League.Ligue1);
            yield return new Team("Envigado FC", EnvigadoFC, League.LigaDimayor);
            yield return new Team("Esbjerg fB", EsbjergfB, League.AlkaSuperliga);
            yield return new Team("ESTAC Troyes", ESTACTroyes, League.DominosLigue2);
            yield return new Team("Estoril Praia", EstorilPraia, League.LigaNOS);
            yield return new Team("Estudiantes de La Plata", EstudiantesdeLaPlata, League.PrimeraDivision);
            yield return new Team("Ettifaq FC", EttifaqFC, League.DawryJameel);
            yield return new Team("Everton", Everton, League.PremierLeague);
            yield return new Team("Excelsior", Excelsior, League.Eredivisie);
            yield return new Team("Exeter City", ExeterCity, League.EFLLeagueTwo);
            yield return new Team("F. Santa Maria da Feira", FSantaMariadaFeira, League.LigaNOS);
            yield return new Team("F.C. Tokyo", FCTokyo, League.MeijiYasudaJ1League);
            yield return new Team("Falkenbergs FF", FalkenbergsFF, League.Allsvenskan);
            yield return new Team("FC Admira Wacker Modling", FCAdmiraWackerModling, League.OBundesliga);
            yield return new Team("FC Anzhi Makhachkala", FCAnzhiMakhachkala, League.RussianLeague);
            yield return new Team("FC Arouca", FCArouca, League.LigaNOS);
            yield return new Team("FC Arsenal Tula", FCArsenalTula, League.RussianLeague);
            yield return new Team("FC Augsburg", FCAugsburg, League.Bundesliga);
            yield return new Team("FC Barcelona", FCBarcelona, League.LaLigaSantander);
            yield return new Team("FC Basel", FCBasel, League.RSL);
            yield return new Team("FC Bayern Munchen", FCBayernMunchen, League.Bundesliga);
            yield return new Team("FC Dallas", FCDallas, League.MLS);
            yield return new Team("FC Erzgebirge Aue", FCErzgebirgeAue, League.Bundesliga2);
            yield return new Team("FC Girondins de Bordeaux", FCGirondinsdeBordeaux, League.Ligue1);
            yield return new Team("FC Groningen", FCGroningen, League.Eredivisie);
            yield return new Team("FC Ingolstadt 04", FCIngolstadt04, League.Bundesliga);
            yield return new Team("FC Kobenhavn", FCKobenhavn, League.AlkaSuperliga);
            yield return new Team("FC Krasnodar", FCKrasnodar, League.RussianLeague);
            yield return new Team("FC Krylya Sovetov Samara", FCKrylyaSovetovSamara, League.RussianLeague);
            yield return new Team("FC Lausanne-Sport", FCLausanneSport, League.RSL);
            yield return new Team("FC Lorient", FCLorient, League.Ligue1);
            yield return new Team("FC Lugano", FCLugano, League.RSL);
            yield return new Team("FC Luzern", FCLuzern, League.RSL);
            yield return new Team("FC Midtjylland", FCMidtjylland, League.AlkaSuperliga);
            yield return new Team("FC Nantes", FCNantes, League.Ligue1);
            yield return new Team("FC Nordsjaelland", FCNordsjaelland, League.AlkaSuperliga);
            yield return new Team("FC Orenburg", FCOrenburg, League.RussianLeague);
            yield return new Team("FC Pacos de Ferreira", FCPacosdeFerreira, League.LigaNOS);
            yield return new Team("FC Porto", FCPorto, League.LigaNOS);
            yield return new Team("FC Red Bull Salzburg", FCRedBullSalzburg, League.OBundesliga);
            yield return new Team("FC Rostov", FCRostov, League.RussianLeague);
            yield return new Team("FC Schalke 04", FCSchalke04, League.Bundesliga);
            yield return new Team("FC Seoul", FCSeoul, League.KLeagueClassic);
            yield return new Team("FC Sion", FCSion, League.RSL);
            yield return new Team("FC Sochaux-Montbeliard", FCSochauxMontbeliard, League.DominosLigue2);
            yield return new Team("FC St. Gallen", FCStGallen, League.RSL);
            yield return new Team("FC St. Pauli Hamburg", FCStPauliHamburg, League.Bundesliga2);
            yield return new Team("FC Thun", FCThun, League.RSL);
            yield return new Team("FC Tom Tomsk", FCTomTomsk, League.RussianLeague);
            yield return new Team("FC Twente", FCTwente, League.Eredivisie);
            yield return new Team("FC Ufa", FCUfa, League.RussianLeague);
            yield return new Team("FC Ural", FCUral, League.RussianLeague);
            yield return new Team("FC Utrecht", FCUtrecht, League.Eredivisie);
            yield return new Team("FC Vaduz", FCVaduz, League.RSL);
            yield return new Team("FC Wurzburger Kickers", FCWurzburgerKickers, League.Bundesliga2);
            yield return new Team("Fenerbahce SK", FenerbahceSK, League.SuperLig);
            yield return new Team("Ferrara", Ferrara, League.CalcioB);
            yield return new Team("Feyenoord", Feyenoord, League.Eredivisie);
            yield return new Team("Finn Harps", FinnHarps, League.SSEAirtricityLeague);
            yield return new Team("Fiorentina", Fiorentina, League.CalcioA);
            yield return new Team("FK Austria Wien", FKAustriaWien, League.OBundesliga);
            yield return new Team("FK Bodo/Glimt", FKBodoGlimt, League.Tippeligaen);
            yield return new Team("FK Haugesund", FKHaugesund, League.Tippeligaen);
            yield return new Team("Fleetwood Town", FleetwoodTown, League.EFLLeagueOne);
            yield return new Team("Football Club de Metz", FootballClubdeMetz, League.Ligue1);
            yield return new Team("Fortaleza CEIF", FortalezaCEIF, League.LigaDimayor);
            yield return new Team("Fortuna Dusseldorf", FortunaDusseldorf, League.Bundesliga2);
            yield return new Team("Frosinone", Frosinone, League.CalcioB);
            yield return new Team("Fulham", Fulham, League.EFLChampionship);
            yield return new Team("Galatasaray SK", GalatasaraySK, League.SuperLig);
            yield return new Team("Galway United", GalwayUnited, League.SSEAirtricityLeague);
            yield return new Team("Gamba Osaka", GambaOsaka, League.MeijiYasudaJ1League);
            yield return new Team("Gazelec Football Club Ajaccio", GazelecFootballClubAjaccio, League.DominosLigue2);
            yield return new Team("Gaziantepspor", Gaziantepspor, League.SuperLig);
            yield return new Team("Gefle IF", GefleIF, League.Allsvenskan);
            yield return new Team("Genclerbirligi SK", GenclerbirligiSK, League.SuperLig);
            yield return new Team("Genoa", Genoa, League.CalcioA);
            yield return new Team("Getafe CF", GetafeCF, League.LaLiga123);
            yield return new Team("GIF Sundsvall", GIFSundsvall, League.Allsvenskan);
            yield return new Team("Gillingham", Gillingham, League.EFLLeagueOne);
            yield return new Team("Gimnasia y Esgrima La Plata", GimnasiayEsgrimaLaPlata, League.PrimeraDivision);
            yield return new Team("Girona FC", GironaFC, League.LaLiga123);
            yield return new Team("Go Ahead Eagles", GoAheadEagles, League.Eredivisie);
            yield return new Team("Godoy Cruz", GodoyCruz, League.PrimeraDivision);
            yield return new Team("Gornik Leczna", GornikLeczna, League.Ekstraklasa);
            yield return new Team("Granada CF", GranadaCF, League.LaLigaSantander);
            yield return new Team("Grasshopper Club Zurich", GrasshopperClubZurich, League.RSL);
            yield return new Team("Grimsby Town", GrimsbyTown, League.EFLLeagueTwo);
            yield return new Team("Guadalajara", Guadalajara, League.LIGABancomerMX);
            yield return new Team("GwangJu FC", GwangJuFC, League.KLeagueClassic);
            yield return new Team("Hamburger SV", HamburgerSV, League.Bundesliga);
            yield return new Team("Hamilton Academical FC", HamiltonAcademicalFC, League.ScottishPremiership);
            yield return new Team("Hammarby IF", HammarbyIF, League.Allsvenskan);
            yield return new Team("Hannover 96", Hannover96, League.Bundesliga2);
            yield return new Team("Hartlepool United", HartlepoolUnited, League.EFLLeagueTwo);
            yield return new Team("Havre Athletic Club", HavreAthleticClub, League.DominosLigue2);
            yield return new Team("Heart of Midlothian", HeartofMidlothian, League.ScottishPremiership);
            yield return new Team("Hellas Verona", HellasVerona, League.CalcioB);
            yield return new Team("Helsingborgs IF", HelsingborgsIF, League.Allsvenskan);
            yield return new Team("Heracles Almelo", HeraclesAlmelo, League.Eredivisie);
            yield return new Team("Hertha Berlin", HerthaBerlin, League.Bundesliga);
            yield return new Team("HJK Helsinki", HJKHelsinki, League.Finnliiga);
            yield return new Team("Houston Dynamo", HoustonDynamo, League.MLS);
            yield return new Team("Huddersfield Town", HuddersfieldTown, League.EFLChampionship);
            yield return new Team("Hull City", HullCity, League.PremierLeague);
            yield return new Team("IF Elfsborg", IFElfsborg, League.Allsvenskan);
            yield return new Team("IFK Goteborg", IFKGoteborg, League.Allsvenskan);
            yield return new Team("IFK Norrkoping", IFKNorrkoping, League.Allsvenskan);
            yield return new Team("IK Start", IKStart, League.Tippeligaen);
            yield return new Team("Incheon United FC", IncheonUnitedFC, League.KLeagueClassic);
            yield return new Team("Independiente", Independiente, League.PrimeraDivision);
            yield return new Team("Independiente Medellin", IndependienteMedellin, League.LigaDimayor);
            yield return new Team("Independiente Santa Fe", IndependienteSantaFe, League.LigaDimayor);
            yield return new Team("Inter", Inter, League.CalcioA);
            yield return new Team("Inverness Caledonian Thistle", InvernessCaledonianThistle, League.ScottishPremiership);
            yield return new Team("Ipswich Town", IpswichTown, League.EFLChampionship);
            yield return new Team("Jagiellonia Bialystok", JagielloniaBialystok, League.Ekstraklasa);
            yield return new Team("Jaguares de Chiapas", JaguaresdeChiapas, League.LIGABancomerMX);
            yield return new Team("Jaguares Futbol Club", JaguaresFutbolClub, League.LigaDimayor);
            yield return new Team("Jeju United FC", JejuUnitedFC, League.KLeagueClassic);
            yield return new Team("Jeonbuk Hyundai Motors", JeonbukHyundaiMotors, League.KLeagueClassic);
            yield return new Team("Jeonnam Dragons", JeonnamDragons, League.KLeagueClassic);
            yield return new Team("Jonkopings Sodra IF", JonkopingsSodraIF, League.Allsvenskan);
            yield return new Team("Jubilo Iwata", JubiloIwata, League.MeijiYasudaJ1League);
            yield return new Team("Junior FC", JuniorFC, League.LigaDimayor);
            yield return new Team("Juventus", Juventus, League.CalcioA);
            yield return new Team("KAA Gent", KAAGent, League.ProLeague);
            yield return new Team("Kaizer Chiefs", KaizerChiefs, League.SouthAfricanFL);
            yield return new Team("Kalmar FF", KalmarFF, League.Allsvenskan);
            yield return new Team("Kardemir Karabukspor", KardemirKarabukspor, League.SuperLig);
            yield return new Team("Karlsruher SC", KarlsruherSC, League.Bundesliga2);
            yield return new Team("KAS Eupen", KASEupen, League.ProLeague);
            yield return new Team("Kashima Antlers", KashimaAntlers, League.MeijiYasudaJ1League);
            yield return new Team("Kashiwa Reysol", KashiwaReysol, League.MeijiYasudaJ1League);
            yield return new Team("Kasimpasa SK", KasimpasaSK, League.SuperLig);
            yield return new Team("Kawasaki Frontale", KawasakiFrontale, League.MeijiYasudaJ1League);
            yield return new Team("Kayserispor", Kayserispor, League.SuperLig);
            yield return new Team("Kilmarnock", Kilmarnock, League.ScottishPremiership);
            yield return new Team("Korona Kielce", KoronaKielce, League.Ekstraklasa);
            yield return new Team("KRC Genk", KRCGenk, League.ProLeague);
            yield return new Team("KV Kortrijk", KVKortrijk, League.ProLeague);
            yield return new Team("KV Mechelen", KVMechelen, League.ProLeague);
            yield return new Team("KV Oostende", KVOostende, League.ProLeague);
            yield return new Team("KVC Westerlo", KVCWesterlo, League.ProLeague);
            yield return new Team("La Equidad", LaEquidad, League.LigaDimayor);
            yield return new Team("LA Galaxy", LAGalaxy, League.MLS);
            yield return new Team("La Spezia", LaSpezia, League.CalcioB);
            yield return new Team("Latina", Latina, League.CalcioB);
            yield return new Team("Lazio", Lazio, League.CalcioA);
            yield return new Team("Lech Poznan", LechPoznan, League.Ekstraklasa);
            yield return new Team("Lechia Gdansk", LechiaGdansk, League.Ekstraklasa);
            yield return new Team("Leeds United", LeedsUnited, League.EFLChampionship);
            yield return new Team("Legends", Legends, League.Legends);
            yield return new Team("Legia Warszawa", LegiaWarszawa, League.Ekstraklasa);
            yield return new Team("Leicester City", LeicesterCity, League.PremierLeague);
            yield return new Team("Levante UD", LevanteUD, League.LaLiga123);
            yield return new Team("Leyton Orient", LeytonOrient, League.EFLLeagueTwo);
            yield return new Team("Lillestrom SK", LillestromSK, League.Tippeligaen);
            yield return new Team("Liniers", Liniers, League.PrimeraDivision);
            yield return new Team("Liverpool", Liverpool, League.PremierLeague);
            yield return new Team("Lokomotiv Moscow", LokomotivMoscow, League.RussianLeague);
            yield return new Team("Longford Town", LongfordTown, League.SSEAirtricityLeague);
            yield return new Team("LOSC Lille", LOSCLille, League.Ligue1);
            yield return new Team("Luton Town", LutonTown, League.EFLLeagueTwo);
            yield return new Team("Lyngby BK", LyngbyBK, League.AlkaSuperliga);
            yield return new Team("Malaga CF", MalagaCF, League.LaLigaSantander);
            yield return new Team("Malmo FF", MalmoFF, League.Allsvenskan);
            yield return new Team("Manchester City", ManchesterCity, League.PremierLeague);
            yield return new Team("Manchester United", ManchesterUnited, League.PremierLeague);
            yield return new Team("Mansfield Town", MansfieldTown, League.EFLLeagueTwo);
            yield return new Team("Medipol Basaksehir FK", MedipolBasaksehirFK, League.SuperLig);
            yield return new Team("Melbourne City", MelbourneCity, League.HyundaiALeague);
            yield return new Team("Melbourne Victory", MelbourneVictory, League.HyundaiALeague);
            yield return new Team("Middlesbrough", Middlesbrough, League.PremierLeague);
            yield return new Team("Milan", Milan, League.CalcioA);
            yield return new Team("Millonarios FC", MillonariosFC, League.LigaDimayor);
            yield return new Team("Millwall", Millwall, League.EFLLeagueOne);
            yield return new Team("Milton Keynes Dons", MiltonKeynesDons, League.EFLLeagueOne);
            yield return new Team("Molde FK", MoldeFK, League.Tippeligaen);
            yield return new Team("Monarcas Morelia", MonarcasMorelia, League.LIGABancomerMX);
            yield return new Team("Monterrey", Monterrey, League.LIGABancomerMX);
            yield return new Team("Montpellier Herault SC", MontpellierHeraultSC, League.Ligue1);
            yield return new Team("Montreal Impact", MontrealImpact, League.MLS);
            yield return new Team("Morecambe", Morecambe, League.EFLLeagueTwo);
            yield return new Team("Moreirense FC", MoreirenseFC, League.LigaNOS);
            yield return new Team("Motherwell", Motherwell, League.ScottishPremiership);
            yield return new Team("N.E.C.", NEC, League.Eredivisie);
            yield return new Team("Nagoya Grampus", NagoyaGrampus, League.MeijiYasudaJ1League);
            yield return new Team("Napoli", Napoli, League.CalcioA);
            yield return new Team("Nastic", Nastic, League.LaLiga123);
            yield return new Team("New England Revolution", NewEnglandRevolution, League.MLS);
            yield return new Team("New York City Football Club", NewYorkCityFootballClub, League.MLS);
            yield return new Team("New York Red Bulls", NewYorkRedBulls, League.MLS);
            yield return new Team("Newcastle Jets", NewcastleJets, League.HyundaiALeague);
            yield return new Team("Newcastle United", NewcastleUnited, League.EFLChampionship);
            yield return new Team("Newell's Old Boys", NewellsOldBoys, League.PrimeraDivision);
            yield return new Team("Newport County", NewportCounty, League.EFLLeagueTwo);
            yield return new Team("Nimes Olympique", NimesOlympique, League.DominosLigue2);
            yield return new Team("Northampton Town", NorthamptonTown, League.EFLLeagueOne);
            yield return new Team("Norwich City", NorwichCity, League.EFLChampionship);
            yield return new Team("Nottingham Forest", NottinghamForest, League.EFLChampionship);
            yield return new Team("Notts County", NottsCounty, League.EFLLeagueTwo);
            yield return new Team("Novara", Novara, League.CalcioB);
            yield return new Team("Odds BK", OddsBK, League.Tippeligaen);
            yield return new Team("Odense Boldklub", OdenseBoldklub, League.AlkaSuperliga);
            yield return new Team("OGC Nice", OGCNice, League.Ligue1);
            yield return new Team("Oldham Athletic", OldhamAthletic, League.EFLLeagueOne);
            yield return new Team("Olympiacos CFP", OlympiacosCFP, League.HellasLiga);
            yield return new Team("Olympique de Marseille", OlympiquedeMarseille, League.Ligue1);
            yield return new Team("Olympique Lyonnais", OlympiqueLyonnais, League.Ligue1);
            yield return new Team("Omiya Ardija", OmiyaArdija, League.MeijiYasudaJ1League);
            yield return new Team("Once Caldas", OnceCaldas, League.LigaDimayor);
            yield return new Team("Orebro SK", OrebroSK, League.Allsvenskan);
            yield return new Team("Orlando City Soccer Club", OrlandoCitySoccerClub, League.MLS);
            yield return new Team("Orlando Pirates", OrlandoPirates, League.SouthAfricanFL);
            yield return new Team("Osmanlispor", Osmanlispor, League.SuperLig);
            yield return new Team("Ostersunds FK", OstersundsFK, League.Allsvenskan);
            yield return new Team("Oxford United", OxfordUnited, League.EFLLeagueOne);
            yield return new Team("Pachuca", Pachuca, League.LIGABancomerMX);
            yield return new Team("Palermo", Palermo, League.CalcioA);
            yield return new Team("Panathinaikos FC", PanathinaikosFC, League.HellasLiga);
            yield return new Team("PAOK", PAOK, League.HellasLiga);
            yield return new Team("Paris Saint-Germain", ParisSaintGermain, League.Ligue1);
            yield return new Team("Partick Thistle F.C.", PartickThistleFC, League.ScottishPremiership);
            yield return new Team("Patriotas Boyaca FC", PatriotasBoyacaFC, League.LigaDimayor);
            yield return new Team("Patronato", Patronato, League.PrimeraDivision);
            yield return new Team("PEC Zwolle", PECZwolle, League.Eredivisie);
            yield return new Team("Perth Glory", PerthGlory, League.HyundaiALeague);
            yield return new Team("Perugia", Perugia, League.CalcioB);
            yield return new Team("Pescara", Pescara, League.CalcioA);
            yield return new Team("Peterborough United", PeterboroughUnited, League.EFLLeagueOne);
            yield return new Team("Philadelphia Union", PhiladelphiaUnion, League.MLS);
            yield return new Team("Piast Gliwice", PiastGliwice, League.Ekstraklasa);
            yield return new Team("Pisa", Pisa, League.CalcioB);
            yield return new Team("Plymouth Argyle", PlymouthArgyle, League.EFLLeagueTwo);
            yield return new Team("Pogon Szczecin", PogonSzczecin, League.Ekstraklasa);
            yield return new Team("Pohang Steelers", PohangSteelers, League.KLeagueClassic);
            yield return new Team("Port Vale", PortVale, League.EFLLeagueOne);
            yield return new Team("Portland Timbers", PortlandTimbers, League.MLS);
            yield return new Team("Portsmouth", Portsmouth, League.EFLLeagueTwo);
            yield return new Team("Preston North End", PrestonNorthEnd, League.EFLChampionship);
            yield return new Team("PSV", PSV, League.Eredivisie);
            yield return new Team("Puebla", Puebla, League.LIGABancomerMX);
            yield return new Team("Queens Park Rangers", QueensParkRangers, League.EFLChampionship);
            yield return new Team("Queretaro", Queretaro, League.LIGABancomerMX);
            yield return new Team("Quilmes Atletico Club", QuilmesAtleticoClub, League.PrimeraDivision);
            yield return new Team("R. Oviedo", ROviedo, League.LaLiga123);
            yield return new Team("R. Sporting", RSporting, League.LaLigaSantander);
            yield return new Team("R. Valladolid CF", RValladolidCF, League.LaLiga123);
            yield return new Team("R. Zaragoza", RZaragoza, League.LaLiga123);
            yield return new Team("Racing Club", RacingClub, League.PrimeraDivision);
            yield return new Team("Racing Club de Lens", RacingClubdeLens, League.DominosLigue2);
            yield return new Team("Randers FC", RandersFC, League.AlkaSuperliga);
            yield return new Team("Rangers FC", RangersFC, League.ScottishPremiership);
            yield return new Team("Rayo Vallecano", RayoVallecano, League.LaLiga123);
            yield return new Team("RB Leipzig", RBLeipzig, League.Bundesliga);
            yield return new Team("RC Celta", RCCelta, League.LaLigaSantander);
            yield return new Team("RC Deportivo", RCDeportivo, League.LaLigaSantander);
            yield return new Team("RC Strasbourg Alsace", RCStrasbourgAlsace, League.DominosLigue2);
            yield return new Team("RCD Espanyol", RCDEspanyol, League.LaLigaSantander);
            yield return new Team("RCD Mallorca", RCDMallorca, League.LaLiga123);
            yield return new Team("Reading", Reading, League.EFLChampionship);
            yield return new Team("Real Betis", RealBetis, League.LaLigaSantander);
            yield return new Team("Real Madrid", RealMadrid, League.LaLigaSantander);
            yield return new Team("Real Salt Lake", RealSaltLake, League.MLS);
            yield return new Team("Real Sociedad", RealSociedad, League.LaLigaSantander);
            yield return new Team("Red Star FC", RedStarFC, League.DominosLigue2);
            yield return new Team("Rio Ave FC", RioAveFC, League.LigaNOS);
            yield return new Team("Rionegro Aguilas", RionegroAguilas, League.LigaDimayor);
            yield return new Team("River Plate", RiverPlate, League.PrimeraDivision);
            yield return new Team("Rochdale", Rochdale, League.EFLLeagueOne);
            yield return new Team("Roda JC Kerkrade", RodaJCKerkrade, League.Eredivisie);
            yield return new Team("Roma", Roma, League.CalcioA);
            yield return new Team("Rosario Central", RosarioCentral, League.PrimeraDivision);
            yield return new Team("Rosenborg BK", RosenborgBK, League.Tippeligaen);
            yield return new Team("Ross County FC", RossCountyFC, League.ScottishPremiership);
            yield return new Team("Rotherham United", RotherhamUnited, League.EFLChampionship);
            yield return new Team("Royal Excel Mouscron", RoyalExcelMouscron, League.ProLeague);
            yield return new Team("RSC Anderlecht", RSCAnderlecht, League.ProLeague);
            yield return new Team("Rubin Kazan", RubinKazan, League.RussianLeague);
            yield return new Team("Ruch Chorzow", RuchChorzow, League.Ekstraklasa);
            yield return new Team("Sagan Tosu", SaganTosu, League.MeijiYasudaJ1League);
            yield return new Team("Salerno", Salerno, League.CalcioB);
            yield return new Team("Sampdoria", Sampdoria, League.CalcioA);
            yield return new Team("San Jose Earthquakes", SanJoseEarthquakes, League.MLS);
            yield return new Team("San Lorenzo de Almagro", SanLorenzodeAlmagro, League.PrimeraDivision);
            yield return new Team("San Luis de Quillota", SanLuisdeQuillota, League.CampScotiabank);
            yield return new Team("San Martin", SanMartin, League.PrimeraDivision);
            yield return new Team("Sanfrecce Hiroshima", SanfrecceHiroshima, League.MeijiYasudaJ1League);
            yield return new Team("Sangju Sangmu FC", SangjuSangmuFC, League.KLeagueClassic);
            yield return new Team("Santiago Wanderers", SantiagoWanderers, League.CampScotiabank);
            yield return new Team("Santos Laguna", SantosLaguna, League.LIGABancomerMX);
            yield return new Team("Sarpsborg 08 FF", Sarpsborg08FF, League.Tippeligaen);
            yield return new Team("Sassuolo", Sassuolo, League.CalcioA);
            yield return new Team("SC Braga", SCBraga, League.LigaNOS);
            yield return new Team("SC Heerenveen", SCHeerenveen, League.Eredivisie);
            yield return new Team("SCR Altach", SCRAltach, League.OBundesliga);
            yield return new Team("Scunthorpe United", ScunthorpeUnited, League.EFLLeagueOne);
            yield return new Team("SD Eibar", SDEibar, League.LaLigaSantander);
            yield return new Team("SD Huesca", SDHuesca, League.LaLiga123);
            yield return new Team("Seattle Sounders FC", SeattleSoundersFC, League.MLS);
            yield return new Team("Seongnam FC", SeongnamFC, League.KLeagueClassic);
            yield return new Team("Sevilla Atletico", SevillaAtletico, League.LaLiga123);
            yield return new Team("Sevilla FC", SevillaFC, League.LaLigaSantander);
            yield return new Team("SG Dynamo Dresden", SGDynamoDresden, League.Bundesliga2);
            yield return new Team("Shakhtar Donetsk", ShakhtarDonetsk, League.UkrayinaLiha);
            yield return new Team("Shamrock Rovers", ShamrockRovers, League.SSEAirtricityLeague);
            yield return new Team("Sheffield United", SheffieldUnited, League.EFLLeagueOne);
            yield return new Team("Sheffield Wednesday", SheffieldWednesday, League.EFLChampionship);
            yield return new Team("Shonan Bellmare", ShonanBellmare, League.MeijiYasudaJ1League);
            yield return new Team("Shrewsbury", Shrewsbury, League.EFLLeagueOne);
            yield return new Team("Silkeborg IF", SilkeborgIF, League.AlkaSuperliga);
            yield return new Team("Sint-Truidense VV", SintTruidenseVV, League.ProLeague);
            yield return new Team("SK Brann", SKBrann, League.Tippeligaen);
            yield return new Team("SK Rapid Wien", SKRapidWien, League.OBundesliga);
            yield return new Team("SK Sturm Graz", SKSturmGraz, League.OBundesliga);
            yield return new Team("SKN St. Polten", SKNStPolten, League.OBundesliga);
            yield return new Team("SL Benfica", SLBenfica, League.LigaNOS);
            yield return new Team("Slask Wroclaw", SlaskWroclaw, League.Ekstraklasa);
            yield return new Team("Sligo Rovers", SligoRovers, League.SSEAirtricityLeague);
            yield return new Team("Sogndal Fotball", SogndalFotball, League.Tippeligaen);
            yield return new Team("SonderjyskE", SonderjyskE, League.AlkaSuperliga);
            yield return new Team("Southampton", Southampton, League.PremierLeague);
            yield return new Team("Southend United", SouthendUnited, League.EFLLeagueOne);
            yield return new Team("Sparta Rotterdam", SpartaRotterdam, League.Eredivisie);
            yield return new Team("Spartak Moscow", SpartakMoscow, League.RussianLeague);
            yield return new Team("Sport-Club Freiburg", SportClubFreiburg, League.Bundesliga);
            yield return new Team("Sporting Charleroi", SportingCharleroi, League.ProLeague);
            yield return new Team("Sporting Club de Bastia", SportingClubdeBastia, League.Ligue1);
            yield return new Team("Sporting CP", SportingCP, League.LigaNOS);
            yield return new Team("Sporting Kansas City", SportingKansasCity, League.MLS);
            yield return new Team("Sporting Lokeren", SportingLokeren, League.ProLeague);
            yield return new Team("SpVgg Greuther Fuerth", SpVggGreutherFuerth, League.Bundesliga2);
            yield return new Team("St. Johnstone FC", StJohnstoneFC, League.ScottishPremiership);
            yield return new Team("St. Patrick's Athletic", StPatricksAthletic, League.SSEAirtricityLeague);
            yield return new Team("Stabaek Fotball", StabaekFotball, League.Tippeligaen);
            yield return new Team("Stade Brestois 29", StadeBrestois29, League.DominosLigue2);
            yield return new Team("Stade de Reims", StadedeReims, League.DominosLigue2);
            yield return new Team("Stade Lavallois Mayenne FC", StadeLavalloisMayenneFC, League.DominosLigue2);
            yield return new Team("Stade Malherbe Caen", StadeMalherbeCaen, League.Ligue1);
            yield return new Team("Stade Rennais FC", StadeRennaisFC, League.Ligue1);
            yield return new Team("Standard de Liege", StandarddeLiege, League.ProLeague);
            yield return new Team("Stevenage", Stevenage, League.EFLLeagueTwo);
            yield return new Team("Stoke City", StokeCity, League.PremierLeague);
            yield return new Team("Stromsgodset IF", StromsgodsetIF, League.Tippeligaen);
            yield return new Team("Sunderland", Sunderland, League.PremierLeague);
            yield return new Team("Suwon FC", SuwonFC, League.KLeagueClassic);
            yield return new Team("Suwon Samsung Bluewings", SuwonSamsungBluewings, League.KLeagueClassic);
            yield return new Team("SV Darmstadt 98", SVDarmstadt98, League.Bundesliga);
            yield return new Team("SV Guntamatic Ried", SVGuntamaticRied, League.OBundesliga);
            yield return new Team("SV Mattersburg", SVMattersburg, League.OBundesliga);
            yield return new Team("SV Sandhausen", SVSandhausen, League.Bundesliga2);
            yield return new Team("SV Werder Bremen", SVWerderBremen, League.Bundesliga);
            yield return new Team("SV Zulte-Waregem", SVZulteWaregem, League.ProLeague);
            yield return new Team("Swansea City", SwanseaCity, League.PremierLeague);
            yield return new Team("Swindon Town", SwindonTown, League.EFLLeagueOne);
            yield return new Team("Sydney FC", SydneyFC, League.HyundaiALeague);
            yield return new Team("Terek Grozny", TerekGrozny, League.RussianLeague);
            yield return new Team("Terni", Terni, League.CalcioB);
            yield return new Team("Tiburones Rojos de Veracruz", TiburonesRojosdeVeracruz, League.LIGABancomerMX);
            yield return new Team("Tigres U.A.N.L.", TigresUANL, League.LIGABancomerMX);
            yield return new Team("Tondela", Tondela, League.LigaNOS);
            yield return new Team("Torino", Torino, League.CalcioA);
            yield return new Team("Toronto FC", TorontoFC, League.MLS);
            yield return new Team("Tottenham Hotspur", TottenhamHotspur, League.PremierLeague);
            yield return new Team("Toulouse Football Club", ToulouseFootballClub, League.Ligue1);
            yield return new Team("Tours Football Club", ToursFootballClub, League.DominosLigue2);
            yield return new Team("Trabzonspor", Trabzonspor, League.SuperLig);
            yield return new Team("Trapani", Trapani, League.CalcioB);
            yield return new Team("Tromso IL", TromsoIL, League.Tippeligaen);
            yield return new Team("TSG 1899 Hoffenheim", TSG1899Hoffenheim, League.Bundesliga);
            yield return new Team("TSV 1860 Munchen", TSV1860Munchen, League.Bundesliga2);
            yield return new Team("U.N.A.M.", UNAM, League.LIGABancomerMX);
            yield return new Team("UCAM Murcia CF", UCAMMurciaCF, League.LaLiga123);
            yield return new Team("UD Almeria", UDAlmeria, League.LaLiga123);
            yield return new Team("UD Las Palmas", UDLasPalmas, League.LaLigaSantander);
            yield return new Team("Udinese", Udinese, League.CalcioA);
            yield return new Team("Ulsan Hyundai Horang-i", UlsanHyundaiHorangi, League.KLeagueClassic);
            yield return new Team("Union de Santa Fe", UniondeSantaFe, League.PrimeraDivision);
            yield return new Team("Union Espanola", UnionEspanola, League.CampScotiabank);
            yield return new Team("Universidad Catolica", UniversidadCatolica, League.CampScotiabank);
            yield return new Team("Universidad de Chile", UniversidaddeChile, League.CampScotiabank);
            yield return new Team("Urawa Red Diamonds", UrawaRedDiamonds, League.MeijiYasudaJ1League);
            yield return new Team("US Orleans Loiret Football", USOrleansLoiretFootball, League.DominosLigue2);
            yield return new Team("Valencia CF", ValenciaCF, League.LaLigaSantander);
            yield return new Team("Valenciennes FC", ValenciennesFC, League.DominosLigue2);
            yield return new Team("Valerenga Fotball", ValerengaFotball, League.Tippeligaen);
            yield return new Team("Vancouver Whitecaps FC", VancouverWhitecapsFC, League.MLS);
            yield return new Team("Vegalta Sendai", VegaltaSendai, League.MeijiYasudaJ1League);
            yield return new Team("Ventforet Kofu", VentforetKofu, League.MeijiYasudaJ1League);
            yield return new Team("Vercelli", Vercelli, League.CalcioB);
            yield return new Team("VfB Stuttgart", VfBStuttgart, League.Bundesliga2);
            yield return new Team("VfL Bochum 1848", VfLBochum1848, League.Bundesliga2);
            yield return new Team("VfL Wolfsburg", VfLWolfsburg, League.Bundesliga);
            yield return new Team("Viborg FF", ViborgFF, League.AlkaSuperliga);
            yield return new Team("Vicenza", Vicenza, League.CalcioB);
            yield return new Team("Victoria", Victoria, League.PrimeraDivision);
            yield return new Team("Viking FK", VikingFK, League.Tippeligaen);
            yield return new Team("Villarreal CF", VillarrealCF, League.LaLigaSantander);
            yield return new Team("Vissel Kobe", VisselKobe, League.MeijiYasudaJ1League);
            yield return new Team("Vitesse", Vitesse, League.Eredivisie);
            yield return new Team("Vitoria Guimaraes", VitoriaGuimaraes, League.LigaNOS);
            yield return new Team("Vitoria Setubal", VitoriaSetubal, League.LigaNOS);
            yield return new Team("Waasland-Beveren", WaaslandBeveren, League.ProLeague);
            yield return new Team("Walsall", Walsall, League.EFLLeagueOne);
            yield return new Team("Watford", Watford, League.PremierLeague);
            yield return new Team("Wellington Phoenix", WellingtonPhoenix, League.HyundaiALeague);
            yield return new Team("West Bromwich Albion", WestBromwichAlbion, League.PremierLeague);
            yield return new Team("West Ham United", WestHamUnited, League.PremierLeague);
            yield return new Team("Western Sydney Wanderers", WesternSydneyWanderers, League.HyundaiALeague);
            yield return new Team("Wexford Youths", WexfordYouths, League.SSEAirtricityLeague);
            yield return new Team("Wigan Athletic", WiganAthletic, League.EFLChampionship);
            yield return new Team("Willem II", WillemII, League.Eredivisie);
            yield return new Team("Wisla Krakow", WislaKrakow, League.Ekstraklasa);
            yield return new Team("Wisla Plock", WislaPlock, League.Ekstraklasa);
            yield return new Team("Wolfsberger AC", WolfsbergerAC, League.OBundesliga);
            yield return new Team("Wolverhampton Wanderers", WolverhamptonWanderers, League.EFLChampionship);
            yield return new Team("Wycombe Wanderers", WycombeWanderers, League.EFLLeagueTwo);
            yield return new Team("Yeovil Town", YeovilTown, League.EFLLeagueTwo);
            yield return new Team("Yokohama F. Marinos", YokohamaFMarinos, League.MeijiYasudaJ1League);
            yield return new Team("Zaglebie Lubin", ZaglebieLubin, League.Ekstraklasa);
            yield return new Team("Zenit St. Petersburg", ZenitStPetersburg, League.RussianLeague);
        }
    }
}
