using System.Collections.Generic;

namespace UltimateTeam.Toolkit.Parameters
{
    public class Team : SearchParameterBase<uint>
    {
        // ReSharper disable InconsistentNaming
        public const uint AaB = 820;
        public const uint AalesundsFK = 1755;
        public const uint Aberdeen = 77;
        public const uint AcademicaCoimbra = 1901;
        public const uint ACAjaccio = 614;
        public const uint ACArlesAvignon = 111989;
        public const uint AccringtonStanley = 110313;
        public const uint ACHorsens = 1446;
        public const uint ADAlcorcon = 100831;
        public const uint AdelaideUnited = 111393;
        public const uint AdmiraWackerModling = 111821;
        public const uint ADODenHaag = 650;
        public const uint AEKAthens = 278;
        public const uint AFCWimbledon = 112259;
        public const uint AGFAarhus = 271;
        public const uint AIK = 433;
        public const uint AJAuxerre = 57;
        public const uint Ajax = 245;
        public const uint AlAhli = 112387;
        public const uint AldershotTown = 382;
        public const uint AlemanniaAachen = 1826;
        public const uint AlEttifaq = 112096;
        public const uint AlFaisaly = 112389;
        public const uint AlFateh = 112390;
        public const uint AlHilal = 605;
        public const uint AlIttihad = 607;
        public const uint AlNassr = 112139;
        public const uint AlRaed = 112392;
        public const uint AlShabab = 111674;
        public const uint Alshoulla = 112407;
        public const uint AlTaawoun = 112393;
        public const uint AlWehdah = 112408;
        public const uint America = 1879;
        public const uint AmericaMineiro = 112001;
        public const uint AmiensSC = 1816;
        public const uint AmkarPerm = 110234;
        public const uint Anderlecht = 229;
        public const uint AngersSCO = 1530;
        public const uint AnzhiMakhachkala = 100766;
        public const uint Arsenal = 1;
        public const uint Ascoli = 1846;
        public const uint ASMonaco = 69;
        public const uint ASNancy = 1823;
        public const uint ASSaintEtienne = 1819;
        public const uint Academica = 1901;
        public const uint AstonVilla = 2;
        public const uint Atalanta = 39;
        public const uint AthleticClubdeBilbao = 448;
        public const uint Atlante = 101116;
        public const uint Atlas = 101114;
        public const uint AtleticodeMadrid = 240;
        public const uint AtleticoGoianiense = 112119;
        public const uint AtleticoMineiro = 1035;
        public const uint AtleticoParanaense = 1039;
        public const uint AtvidabergsFF = 111835;
        public const uint AustriaWien = 256;
        public const uint Avai = 111976;
        public const uint AVladikavkaz = 110230;
        public const uint AZ = 1906;
        public const uint Bahia = 1598;
        public const uint Bari = 1848;
        public const uint Barnet = 135;
        public const uint Barnsley = 1932;
        public const uint Bayer04Leverkusen = 32;
        public const uint BirminghamCity = 88;
        public const uint BKHacken = 711;
        public const uint BlackburnRovers = 3;
        public const uint Blackpool = 1926;
        public const uint BohemianFC = 305;
        public const uint Bologna = 189;
        public const uint BoltonWanderers = 4;
        public const uint BorussiaDortmund = 22;
        public const uint BorussiaMgladbach = 23;
        public const uint Botafogo = 517;
        public const uint Bournemouth = 1943;
        public const uint BradfordCity = 1804;
        public const uint Braga = 1896;
        public const uint BrayWanderers = 838;
        public const uint Brentford = 1925;
        public const uint Brescia = 190;
        public const uint BrightonHoveAlbion = 1808;
        public const uint BrisbaneRoar = 111395;
        public const uint BristolCity = 1919;
        public const uint BristolRovers = 1962;
        public const uint Brondby = 269;
        public const uint BSCYoungBoys = 900;
        public const uint Burnley = 1796;
        public const uint BurtonAlbion = 15015;
        public const uint Bury = 1945;
        public const uint BusanIPark = 1476;
        public const uint Cagliari = 1842;
        public const uint CAOsasuna = 479;
        public const uint CardiffCity = 1961;
        public const uint CarlisleUnited = 1480;
        public const uint Catania = 110364;
        public const uint CDAlcoyano = 110833;
        public const uint CDFeirense = 10019;
        public const uint CDGuadalajaraSpain = 111827;
        public const uint CDLugo = 110831;
        public const uint CDMirandes = 110069;
        public const uint CDNacional = 1891;
        public const uint CDNacionaldeMadeira = 1891;
        public const uint CDNumancia = 477;
        public const uint CDTenerife = 260;
        public const uint Ceara = 111059;
        public const uint Celtic = 78;
        public const uint CentralCoastMariners = 111396;
        public const uint CercleBrugge = 1750;
        public const uint CESabadell = 15021;
        public const uint Cesena = 110915;
        public const uint ChamNiortais = 1813;
        public const uint Charleroi = 670;
        public const uint CharltonAthletic = 89;
        public const uint Chelsea = 5;
        public const uint CheltenhamTown = 1936;
        public const uint Chesterfield = 1924;
        public const uint ChicagoFire = 693;
        public const uint ChievoVerona = 192;
        public const uint ChivasUSA = 111070;
        public const uint ChunnamDragons = 1475;
        public const uint Cittadella = 111993;
        public const uint ClermontFoot = 1815;
        public const uint ClubBrugge = 231;
        public const uint ClubLeon = 110781;
        public const uint ColchesterUnited = 1935;
        public const uint ColoradoRapids = 694;
        public const uint ColumbusCrew = 687;
        public const uint CordobaCF = 1867;
        public const uint Corinthians = 1041;
        public const uint Coritiba = 111044;
        public const uint CorkCity = 422;
        public const uint CoventryCity = 1800;
        public const uint CracoviaKrakow = 110747;
        public const uint CrawleyTown = 110890;
        public const uint CreweAlexandra = 121;
        public const uint Crotone = 110734;
        public const uint CruzAzul = 1878;
        public const uint Cruzeiro = 568;
        public const uint CrystalPalace = 1799;
        public const uint CSKAMoskva = 315;
        public const uint CFunchal = 1893;
        public const uint CSSedan = 613;
        public const uint DaeguFC = 2056;
        public const uint DaejeonCitizen = 980;
        public const uint DagenhamRedbridge = 373;
        public const uint DCUnited = 688;
        public const uint DeGraafschap = 635;
        public const uint DerbyCounty = 91;
        public const uint DerryCity = 445;
        public const uint DijonFootball = 110569;
        public const uint DinamoMoskva = 312;
        public const uint DjurgardensIF = 710;
        public const uint DoncasterRovers = 142;
        public const uint DroghedaUnited = 1572;
        public const uint DundalkFC = 837;
        public const uint DundeeFC = 180;
        public const uint DundeeUnited = 181;
        public const uint DynamoDresden = 503;
        public const uint EintrachtBraunschweig = 110500;
        public const uint EintrachtFrankfurt = 1824;
        public const uint ElcheCF = 468;
        public const uint Empoli = 1746;
        public const uint EnAvantGuingamp = 62;
        public const uint EnergieCottbus = 162;
        public const uint ErzgebirgeAue = 506;
        public const uint Esbjerg = 1445;
        public const uint Estoril = 10020;
        public const uint ESTroyes = 294;
        public const uint EstudiantesTecos = 110780;
        public const uint Everton = 7;
        public const uint EvianThononGaillardFC = 111271;
        public const uint Excelsior = 1971;
        public const uint ExeterCity = 143;
        public const uint FCAugsburg = 100409;
        public const uint FCBarcelona = 241;
        public const uint FCBarcelonaB = 110704;
        public const uint FCBasel = 896;
        public const uint FCBayern = 21;
        public const uint FCCartagena = 100851;
        public const uint FCCopenhagen = 819;
        public const uint FCDallas = 695;
        public const uint FCGroningen = 1915;
        public const uint FCIngolstadt04 = 111239;
        public const uint FCIstres = 1820;
        public const uint FCKaiserslautern = 29;
        public const uint FCKoln = 31;
        public const uint FCKrasnodar = 112218;
        public const uint FCLausanneSports = 1862;
        public const uint FCLorient = 217;
        public const uint FCLuzern = 897;
        public const uint FCMetz = 68;
        public const uint FCMidtjylland = 1516;
        public const uint FCNantes = 71;
        public const uint FCNordsjlland = 1788;
        public const uint FCNurnberg = 171;
        public const uint FCPaosdeFerreira = 182;
        public const uint FCPorto = 236;
        public const uint FCRostov = 110231;
        public const uint FCSchalke04 = 34;
        public const uint FCSeoul = 982;
        public const uint FCSion = 110770;
        public const uint FCSochaux = 226;
        public const uint FCStGallen = 898;
        public const uint FCStPauli = 110329;
        public const uint FCThun = 1715;
        public const uint FCTwente = 1908;
        public const uint FCUnionBerlin = 1831;
        public const uint FCUtrecht = 1903;
        public const uint FCVolgaNizhniyNovgorod = 112217;
        public const uint FCZurich = 894;
        public const uint Feyenoord = 246;
        public const uint Figueirense = 111045;
        public const uint Fiorentina = 110374;
        public const uint FKHaugesund = 1463;
        public const uint Flamengo = 1043;
        public const uint FleetwoodTown = 112260;
        public const uint Fluminense = 567;
        public const uint FortunaDsseldorf = 110636;
        public const uint FredrikstadFK = 2041;
        public const uint FSVFrankfurt = 110596;
        public const uint FSVMainz05 = 169;
        public const uint Fulham = 144;
        public const uint GAIS = 111594;
        public const uint GalatasaraySK = 325;
        public const uint GalwayUnited = 1571;
        public const uint GangwonFC = 112115;
        public const uint GazelecAjaccio = 110316;
        public const uint GefleIF = 111277;
        public const uint Genk = 673;
        public const uint Genoa = 110556;
        public const uint Gent = 674;
        public const uint GetafeCF = 1860;
        public const uint GIFSundsvall = 1596;
        public const uint Gillingham = 1802;
        public const uint GilVicente = 1888;
        public const uint GilVicenteFC = 1888;
        public const uint GironaFC = 110062;
        public const uint GirondinsBordeaux = 59;
        public const uint GKSBelchatow = 110744;
        public const uint Gliwice = 111086;
        public const uint GoldCoastUnited = 112078;
        public const uint GornikZabrze = 420;
        public const uint GranadaCF = 110832;
        public const uint GrasshopperClub = 322;
        public const uint Gremio = 1629;
        public const uint Grosseto = 111491;
        public const uint Guadalajara = 1880;
        public const uint Guimaraes = 1887;
        public const uint GwangJuFC = 112258;
        public const uint GyeongNamFC = 111588;
        public const uint Hajer = 112394;
        public const uint HalmstadsBK = 321;
        public const uint HamburgerSV = 28;
        public const uint Hannover96 = 485;
        public const uint HansaRostock = 27;
        public const uint HartlepoolUnited = 1941;
        public const uint HeartofMidlothian = 80;
        public const uint HelsingborgsIF = 432;
        public const uint HeraclesAlmelo = 100634;
        public const uint HerculesCF = 100879;
        public const uint HerefordUnited = 147;
        public const uint HerthaBSC = 166;
        public const uint Hibernian = 81;
        public const uint Hoffenheim = 10029;
        public const uint HonefossBK = 1841;
        public const uint HoustonDynamo = 698;
        public const uint HuddersfieldTown = 1939;
        public const uint HullCity = 1952;
        public const uint IFElfsborg = 700;
        public const uint IFKGoteborg = 319;
        public const uint IFKNorrkoping = 702;
        public const uint IKStart = 1524;
        public const uint IncheonUnitedFC = 110765;
        public const uint Inter = 44;
        public const uint Internacional = 1048;
        public const uint InvernessCaledonianThistle = 620;
        public const uint IpswichTown = 94;
        public const uint JagielloniaBialystok = 110745;
        public const uint JaguaresdeChiapas = 110151;
        public const uint JejuUnitedFC = 1478;
        public const uint JeonbukHyundaiMotors = 1477;
        public const uint Juventus = 45;
        public const uint JuveStabia = 112124;
        public const uint KaizerChiefs = 110929;
        public const uint KalmarFF = 1439;
        public const uint KapfenbergerSV = 15011;
        public const uint KarlsruherSC = 1832;
        public const uint Kilmarnock = 82;
        public const uint KoronaKielce = 111083;
        public const uint Kortrijk = 100081;
        public const uint KrylyaSovetovSamara = 100764;
        public const uint KubanKrasnodar = 110089;
        public const uint Lanciano = 112020;
        public const uint LaSpezia = 110741;
        public const uint Lazio = 46;
        public const uint LBChateauroux = 212;
        public const uint Lecce = 347;
        public const uint LechiaGdansk = 111091;
        public const uint LechPoznan = 873;
        public const uint LeedsUnited = 8;
        public const uint LegiaWarszawa = 1871;
        public const uint LeHavreAC = 1738;
        public const uint LeicesterCity = 95;
        public const uint LeMansFC = 1739;
        public const uint LevanteUD = 1853;
        public const uint LeytonOrient = 1958;
        public const uint Lierse = 239;
        public const uint LillestromSK = 299;
        public const uint Liverpool = 9;
        public const uint Livorno = 1844;
        public const uint LKSLodz = 111085;
        public const uint Lokeren = 2007;
        public const uint LokomotivMoskva = 100765;
        public const uint LosAngelesGalaxy = 697;
        public const uint LOSCLille = 65;
        public const uint MacclesfieldTown = 1959;
        public const uint MalagaCF = 573;
        public const uint MalmoFF = 320;
        public const uint ManchesterCity = 10;
        public const uint ManchesterUnited = 11;
        public const uint Mechelen = 110724;
        public const uint MelbourneHeart = 112224;
        public const uint MelbourneVictory = 111397;
        public const uint Middlesbrough = 12;
        public const uint Milan = 47;
        public const uint Millwall = 97;
        public const uint MiltonKeynesDons = 1798;
        public const uint MjallbyAIF = 112072;
        public const uint Modena = 1744;
        public const uint MoldeFK = 417;
        public const uint MonarcasMorelia = 1028;
        public const uint Monterrey = 1032;
        public const uint MontpellierSC = 70;
        public const uint MontrealImpact = 111139;
        public const uint MordovSaransk = 110106;
        public const uint Morecambe = 357;
        public const uint MoreiraConegos = 1900;
        public const uint Motherwell = 83;
        public const uint MSVDuisburg = 1825;
        public const uint NACBreda = 1904;
        public const uint Najran = 112395;
        public const uint Napoli = 48;
        public const uint NasticdeTarragona = 15019;
        public const uint NEC = 1910;
        public const uint NeuchatelXamax = 435;
        public const uint NewcastleUnited = 13;
        public const uint NewcastleUnitedJets = 111398;
        public const uint NewEnglandRevolution = 691;
        public const uint NewYorkRedBulls = 689;
        public const uint NimesOlympique = 224;
        public const uint NorthamptonTown = 1930;
        public const uint NorwichCity = 1792;
        public const uint NottinghamForest = 14;
        public const uint NottsCounty = 1937;
        public const uint Novara = 112225;
        public const uint NRecife = 111050;
        public const uint OddGrenland = 1456;
        public const uint OdenseBK = 272;
        public const uint OGCNice = 72;
        public const uint OldhamAthletic = 1920;
        public const uint Olhanense = 111540;
        public const uint Olympiakos = 280;
        public const uint OlympiquedeMarseille = 219;
        public const uint OlympiqueLyonnais = 66;
        public const uint OrebroSK = 705;
        public const uint OrlandoPirates = 110930;
        public const uint OudHeverleeLeuven = 100087;
        public const uint OxfordUnited = 1951;
        public const uint Pachuca = 110147;
        public const uint PacosFerreira = 1892;
        public const uint Padova = 110912;
        public const uint Palermo = 1843;
        public const uint Palmeiras = 383;
        public const uint Panathinaikos = 1884;
        public const uint PAOK = 393;
        public const uint ParisSaintGermain = 73;
        public const uint Parma = 50;
        public const uint PCampinas = 111043;
        public const uint PECZwolle = 1914;
        public const uint PerthGlory = 111399;
        public const uint Pescara = 200;
        public const uint PeterboroughUnited = 1938;
        public const uint PhiladelphiaUnion = 112134;
        public const uint PlymouthArgyle = 1929;
        public const uint PodbeskidzieBielskoBiala = 111087;
        public const uint PohangSteelers = 1474;
        public const uint PoloniaWarszawa = 1570;
        public const uint PortlandTimbers = 111140;
        public const uint Portsmouth = 1790;
        public const uint Portuguesa = 111292;
        public const uint PortVale = 1928;
        public const uint PrestonNorthEnd = 1801;
        public const uint PSV = 247;
        public const uint Puebla = 110152;
        public const uint QueensParkRangers = 15;
        public const uint Queretaro = 110150;
        public const uint RacingClubdeLens = 64;
        public const uint RacingdeSantander = 456;
        public const uint RandersFC = 1786;
        public const uint RapidWien = 254;
        public const uint RayoVallecano = 480;
        public const uint RCCeltadeVigo = 450;
        public const uint RCDeportivo = 242;
        public const uint RCDEspanyol = 452;
        public const uint RCDMallorca = 453;
        public const uint RCRecreativo = 571;
        public const uint Reading = 1793;
        public const uint RealBetisBalompie = 449;
        public const uint RealMadrid = 243;
        public const uint RealMurciaCF = 1855;
        public const uint RealSaltLake = 111065;
        public const uint RealSociedad = 457;
        public const uint RealSportingdeGijon = 459;
        public const uint RealValladolid = 462;
        public const uint RealZaragoza = 244;
        public const uint RedBullSalzburg = 191;
        public const uint Reggina = 203;
        public const uint RioAveFC = 744;
        public const uint RKCWaalwijk = 1905;
        public const uint RMCastilla = 110710;
        public const uint Rochdale = 1955;
        public const uint RodaJCKerkrade = 1902;
        public const uint Roma = 52;
        public const uint RosenborgBK = 298;
        public const uint RossCounty = 631;
        public const uint RotherhamUnited = 1797;
        public const uint RubinKazan = 110227;
        public const uint RuchChorzow = 874;
        public const uint Sampdoria = 1837;
        public const uint SandnesUlf = 112374;
        public const uint SangjuSangmuPhoenixFC = 2055;
        public const uint SanJoseEarthquakes = 111928;
        public const uint SanLuis = 110149;
        public const uint Santos = 1053;
        public const uint SantosLaguna = 110144;
        public const uint SaoPaulo = 598;
        public const uint Sassuolo = 111974;
        public const uint SCBastia = 58;
        public const uint SCBeiraMar = 1897;
        public const uint SCBraga = 1896;
        public const uint SCFreiburg = 25;
        public const uint SCHeerenveen = 1913;
        public const uint SCOlhanense = 111540;
        public const uint SCPaderborn = 10030;
        public const uint ScunthorpeUnited = 1949;
        public const uint SCWienerNeustadt = 111373;
        public const uint SDHuesca = 110839;
        public const uint SDPonferradina = 2023;
        public const uint SeattleSounders = 111144;
        public const uint SeongnamIlhwaChunma = 981;
        public const uint ServetteFC = 324;
        public const uint SevillaFC = 481;
        public const uint ShamrockRovers = 306;
        public const uint SheffieldUnited = 1794;
        public const uint SheffieldWednesday = 1807;
        public const uint Shelbourne = 834;
        public const uint ShrewsburyTown = 127;
        public const uint Siena = 1838;
        public const uint SilkeborgIF = 270;
        public const uint SKBrann = 919;
        public const uint SlaskWroclaw = 111092;
        public const uint SLBenfica = 234;
        public const uint SligoRovers = 563;
        public const uint SMCaen = 210;
        public const uint Snderjyske = 1447;
        public const uint SogndalFotball = 1465;
        public const uint Southampton = 17;
        public const uint SouthendUnited = 1954;
        public const uint SpartakMoskva = 100767;
        public const uint SpartakNalchik = 110103;
        public const uint SportingCP = 237;
        public const uint SportingKC = 696;
        public const uint SportingLisbon = 237;
        public const uint SPVGGGreutherFrth = 165;
        public const uint SRecife = 111057;
        public const uint SSVJahn = 543;
        public const uint StabaekFotball = 917;
        public const uint StadeBrestois = 378;
        public const uint StadedeReims = 379;
        public const uint StadeLavallois = 1814;
        public const uint StadeRennais = 74;
        public const uint Standard = 232;
        public const uint Stevenage = 361;
        public const uint StJohnstone = 100804;
        public const uint StMirren = 100805;
        public const uint StokeCity = 1806;
        public const uint StPatricksAthletic = 423;
        public const uint StromsgodsetToppfotball = 922;
        public const uint SturmGraz = 209;
        public const uint Sunderland = 106;
        public const uint SuwonSamsungBluewings = 983;
        public const uint SVMattersburg = 1785;
        public const uint SVRied = 780;
        public const uint SVSandhausen = 110178;
        public const uint SwanseaCity = 1960;
        public const uint SwindonTown = 1934;
        public const uint SydneyFC = 111400;
        public const uint SyrianskaFC = 112267;
        public const uint Szczecin = 110746;
        public const uint TerekGrozny = 110109;
        public const uint Terni = 570;
        public const uint TigresUANL = 1970;
        public const uint Toluca = 1882;
        public const uint TomTomsk = 110233;
        public const uint Torino = 54;
        public const uint TorontoFC = 111651;
        public const uint TorquayUnited = 1946;
        public const uint TottenhamHotspur = 18;
        public const uint ToulouseFC = 1809;
        public const uint ToursFC = 110326;
        public const uint TranmereRovers = 15048;
        public const uint TromsoIL = 418;
        public const uint TSV1860Munchen = 33;
        public const uint UCD = 111132;
        public const uint UDAlmeria = 1861;
        public const uint Udinese = 55;
        public const uint UDLasPalmas = 472;
        public const uint UlsanHyundaiFC = 1473;
        public const uint UNAM = 1881;
        public const uint UniaoDesportivadeLeiria = 1895;
        public const uint USBoulogne = 111376;
        public const uint ValenciaCF = 461;
        public const uint ValenciennesFC = 110456;
        public const uint ValerengaFotball = 920;
        public const uint VancouverWhitecaps = 101112;
        public const uint Varese = 112237;
        public const uint VascodaGama = 569;
        public const uint Vercelli = 112398;
        public const uint Verona = 206;
        public const uint VfBStuttgart = 36;
        public const uint VfLBochum = 160;
        public const uint VfLWolfsburg = 175;
        public const uint VfRAalen = 550;
        public const uint Vicenza = 1847;
        public const uint VikingFK = 300;
        public const uint VillarrealB = 110902;
        public const uint VillarrealCF = 483;
        public const uint Vitesse = 1909;
        public const uint VitoriaGuimaraes = 1887;
        public const uint VitoriaSetubal = 665;
        public const uint VVVVenlo = 100651;
        public const uint WaaslandBeveren = 110913;
        public const uint WackerInnsbruck = 2045;
        public const uint Walsall = 1803;
        public const uint WanderersFC = 112427;
        public const uint Waregem = 15005;
        public const uint Watford = 1795;
        public const uint WellingtonPhoenix = 111766;
        public const uint WerderBremen = 38;
        public const uint WestBromwichAlbion = 109;
        public const uint WestHamUnited = 19;
        public const uint WidzewLodz = 301;
        public const uint WiganAthletic = 1917;
        public const uint WillemII = 1907;
        public const uint WislaKrakow = 1873;
        public const uint WolfsbergerAC = 111822;
        public const uint WolverhamptonWanderers = 110;
        public const uint WycombeWanderers = 1933;
        public const uint XerezCD = 1742;
        public const uint XoloitzcuintlesdeTijuana = 111678;
        public const uint YeovilTown = 346;
        public const uint YorkCity = 1948;
        public const uint ZaglebieLubin = 110749;
        public const uint ZenitStPetersburg = 100769;
        // ReSharper restore InconsistentNaming

        private Team(string description, uint value, uint league)
        {
            Description = description;
            Value = value;
            Parent = league;
        }

        public static IEnumerable<Team> GetAll()
        {
            yield return new Team("1. FC Kaiserslautern", FCKaiserslautern, League.Bundesliga2);
            yield return new Team("1. FC Koln", FCKoln, League.Bundesliga2);
            yield return new Team("1. FC Nurnberg", FCNurnberg, League.Bundesliga);
            yield return new Team("1. FC Union Berlin", FCUnionBerlin, League.Bundesliga2);
            yield return new Team("1. FSV Mainz 05", FSVMainz05, League.Bundesliga);
            yield return new Team("1899 Hoffenheim", Hoffenheim, League.Bundesliga);
            yield return new Team("A. Vladikavkaz", AVladikavkaz, League.RussianLeague);
            yield return new Team("AaB", AaB, League.Superliga);
            yield return new Team("Aalesunds FK", AalesundsFK, League.Tippeligaen);
            yield return new Team("Aberdeen", Aberdeen, League.Spl);
            yield return new Team("AC Ajaccio", ACAjaccio, League.Ligue1);
            yield return new Team("AC Arles-Avignon", ACArlesAvignon, League.Ligue2);
            yield return new Team("AC Horsens", ACHorsens, League.Superliga);
            yield return new Team("Academica Coimbra", AcademicaCoimbra, League.LigaPortuguesa);
            yield return new Team("Accrington Stanley", AccringtonStanley, League.NpowerLeague2);
            yield return new Team("AD Alcorcon", ADAlcorcon, League.LigaAdelante);
            yield return new Team("Adelaide United", AdelaideUnited, League.ALeague);
            yield return new Team("Admira Wacker Modling", AdmiraWackerModling, League.Abundesliga);
            yield return new Team("ADO Den Haag", ADODenHaag, League.Eredivisie);
            yield return new Team("AEK Athens", AEKAthens, League.HellasLiga);
            yield return new Team("AFC Wimbledon", AFCWimbledon, League.NpowerLeague2);
            yield return new Team("AGF Aarhus", AGFAarhus, League.Superliga);
            yield return new Team("AIK", AIK, League.Allsvenskan);
            yield return new Team("AJ Auxerre", AJAuxerre, League.Ligue2);
            yield return new Team("Ajax", Ajax, League.Eredivisie);
            yield return new Team("Al Wehdah", AlWehdah, League.SaudiProLeague);
            yield return new Team("Al-Ahli", AlAhli, League.SaudiProLeague);
            yield return new Team("Aldershot Town", AldershotTown, League.NpowerLeague2);
            yield return new Team("Alemannia Aachen", AlemanniaAachen, League.Bundesliga2);
            yield return new Team("Al-Ettifaq", AlEttifaq, League.SaudiProLeague);
            yield return new Team("Al-Faisaly", AlFaisaly, League.SaudiProLeague);
            yield return new Team("Al-Fateh", AlFateh, League.SaudiProLeague);
            yield return new Team("Al-Hilal", AlHilal, League.SaudiProLeague);
            yield return new Team("Al-Ittihad", AlIttihad, League.SaudiProLeague);
            yield return new Team("Al-Nassr", AlNassr, League.SaudiProLeague);
            yield return new Team("Al-Raed", AlRaed, League.SaudiProLeague);
            yield return new Team("Al-Shabab", AlShabab, League.SaudiProLeague);
            yield return new Team("Alshoulla", Alshoulla, League.SaudiProLeague);
            yield return new Team("Al-Taawoun", AlTaawoun, League.SaudiProLeague);
            yield return new Team("America Mineiro", AmericaMineiro, League.LigadoBrasil);
            yield return new Team("America", America, League.LigaMx);
            yield return new Team("Amiens SC", AmiensSC, League.Ligue2);
            yield return new Team("Amkar Perm", AmkarPerm, League.RussianLeague);
            yield return new Team("Anderlecht", Anderlecht, League.ProLeague);
            yield return new Team("Angers SCO", AngersSCO, League.Ligue2);
            yield return new Team("Anzhi Makhachkala", AnzhiMakhachkala, League.RussianLeague);
            yield return new Team("Arsenal", Arsenal, League.BarclaysPremierLeague);
            yield return new Team("AS Monaco", ASMonaco, League.Ligue2);
            yield return new Team("AS Nancy", ASNancy, League.Ligue1);
            yield return new Team("AS Saint-Etienne", ASSaintEtienne, League.Ligue1);
            yield return new Team("Ascoli", Ascoli, League.SerieB);
            yield return new Team("Acadmica", Academica, League.LigaPortuguesa);
            yield return new Team("Aston Villa", AstonVilla, League.BarclaysPremierLeague);
            yield return new Team("Atalanta", Atalanta, League.SerieA);
            yield return new Team("Athletic Club de Bilbao", AthleticClubdeBilbao, League.LigaBbva);
            yield return new Team("Atlante", Atlante, League.LigaMx);
            yield return new Team("Atlas", Atlas, League.LigaMx);
            yield return new Team("Atletico de Madrid", AtleticodeMadrid, League.LigaBbva);
            yield return new Team("Atletico Goianiense", AtleticoGoianiense, League.LigadoBrasil);
            yield return new Team("Atletico Mineiro", AtleticoMineiro, League.LigadoBrasil);
            yield return new Team("Atletico Paranaense", AtleticoParanaense, League.LigadoBrasil);
            yield return new Team("Atvidabergs FF", AtvidabergsFF, League.Allsvenskan);
            yield return new Team("Austria Wien", AustriaWien, League.Abundesliga);
            yield return new Team("Avai", Avai, League.LigadoBrasil);
            yield return new Team("AZ", AZ, League.Eredivisie);
            yield return new Team("Bahia", Bahia, League.LigadoBrasil);
            yield return new Team("Bari", Bari, League.SerieB);
            yield return new Team("Barnet", Barnet, League.NpowerLeague2);
            yield return new Team("Barnsley", Barnsley, League.NpowerChampionship);
            yield return new Team("Bayer 04 Leverkusen", Bayer04Leverkusen, League.Bundesliga);
            yield return new Team("SC Beira Mar", SCBeiraMar, League.LigaPortuguesa);
            yield return new Team("Birmingham City", BirminghamCity, League.NpowerChampionship);
            yield return new Team("BK Hacken", BKHacken, League.Allsvenskan);
            yield return new Team("Blackburn Rovers", BlackburnRovers, League.NpowerChampionship);
            yield return new Team("Blackpool", Blackpool, League.NpowerChampionship);
            yield return new Team("Bohemian FC", BohemianFC, League.AirtricityLeague);
            yield return new Team("Bologna", Bologna, League.SerieA);
            yield return new Team("Bolton Wanderers", BoltonWanderers, League.NpowerChampionship);
            yield return new Team("Borussia Dortmund", BorussiaDortmund, League.Bundesliga);
            yield return new Team("Borussia M'gladbach", BorussiaMgladbach, League.Bundesliga);
            yield return new Team("Botafogo", Botafogo, League.LigadoBrasil);
            yield return new Team("Bournemouth", Bournemouth, League.NpowerLeague1);
            yield return new Team("Bradford City", BradfordCity, League.NpowerLeague2);
            yield return new Team("Bray Wanderers", BrayWanderers, League.AirtricityLeague);
            yield return new Team("Brentford", Brentford, League.NpowerLeague1);
            yield return new Team("Brescia", Brescia, League.SerieB);
            yield return new Team("Brighton & Hove Albion", BrightonHoveAlbion, League.NpowerChampionship);
            yield return new Team("Brisbane Roar", BrisbaneRoar, League.ALeague);
            yield return new Team("Bristol City", BristolCity, League.NpowerChampionship);
            yield return new Team("Bristol Rovers", BristolRovers, League.NpowerLeague2);
            yield return new Team("Brondby", Brondby, League.Superliga);
            yield return new Team("BSC Young Boys", BSCYoungBoys, League.RaiffeisenSl);
            yield return new Team("Burnley", Burnley, League.NpowerChampionship);
            yield return new Team("Burton Albion", BurtonAlbion, League.NpowerLeague2);
            yield return new Team("Bury", Bury, League.NpowerLeague1);
            yield return new Team("Busan I'Park", BusanIPark, League.KLeague);
            yield return new Team("CA Osasuna", CAOsasuna, League.LigaBbva);
            yield return new Team("Cagliari", Cagliari, League.SerieA);
            yield return new Team("Cardiff City", CardiffCity, League.NpowerChampionship);
            yield return new Team("Carlisle United", CarlisleUnited, League.NpowerLeague1);
            yield return new Team("Catania", Catania, League.SerieA);
            yield return new Team("CD Alcoyano", CDAlcoyano, League.LigaAdelante);
            yield return new Team("CD Feirense", CDFeirense, League.LigaPortuguesa);
            yield return new Team("CD Guadalajara (Spain)", CDGuadalajaraSpain, League.LigaAdelante);
            yield return new Team("CD Lugo", CDLugo, League.LigaAdelante);
            yield return new Team("CD Mirandes", CDMirandes, League.LigaAdelante);
            yield return new Team("CD Nacional", CDNacional, League.LigaPortuguesa);
            yield return new Team("CD Numancia", CDNumancia, League.LigaAdelante);
            yield return new Team("CD Tenerife", CDTenerife, League.LigaAdelante);
            yield return new Team("CE Sabadell", CESabadell, League.LigaAdelante);
            yield return new Team("Ceara", Ceara, League.LigadoBrasil);
            yield return new Team("Celtic", Celtic, League.Spl);
            yield return new Team("Central Coast Mariners", CentralCoastMariners, League.ALeague);
            yield return new Team("Cercle Brugge", CercleBrugge, League.ProLeague);
            yield return new Team("Cesena", Cesena, League.SerieB);
            yield return new Team("Cham. Niortais", ChamNiortais, League.Ligue2);
            yield return new Team("Charleroi", Charleroi, League.ProLeague);
            yield return new Team("Charlton Athletic", CharltonAthletic, League.NpowerChampionship);
            yield return new Team("Chelsea", Chelsea, League.BarclaysPremierLeague);
            yield return new Team("Cheltenham Town", CheltenhamTown, League.NpowerLeague2);
            yield return new Team("Chesterfield", Chesterfield, League.NpowerLeague2);
            yield return new Team("Chicago Fire", ChicagoFire, League.Mls);
            yield return new Team("Chievo Verona", ChievoVerona, League.SerieA);
            yield return new Team("Chivas USA", ChivasUSA, League.Mls);
            yield return new Team("Chunnam Dragons", ChunnamDragons, League.KLeague);
            yield return new Team("Cittadella", Cittadella, League.SerieB);
            yield return new Team("Clermont Foot", ClermontFoot, League.Ligue2);
            yield return new Team("Club Brugge", ClubBrugge, League.ProLeague);
            yield return new Team("Club Leon", ClubLeon, League.LigaMx);
            yield return new Team("Colchester United", ColchesterUnited, League.NpowerLeague1);
            yield return new Team("Colorado Rapids", ColoradoRapids, League.Mls);
            yield return new Team("Columbus Crew", ColumbusCrew, League.Mls);
            yield return new Team("Cordoba CF", CordobaCF, League.LigaAdelante);
            yield return new Team("Corinthians", Corinthians, League.LigadoBrasil);
            yield return new Team("Coritiba", Coritiba, League.LigadoBrasil);
            yield return new Team("Cork City", CorkCity, League.AirtricityLeague);
            yield return new Team("Coventry City", CoventryCity, League.NpowerLeague1);
            yield return new Team("Cracovia Krakow", CracoviaKrakow, League.PolskaLiga);
            yield return new Team("Crawley Town", CrawleyTown, League.NpowerLeague1);
            yield return new Team("Crewe Alexandra", CreweAlexandra, League.NpowerLeague1);
            yield return new Team("Crotone", Crotone, League.SerieB);
            yield return new Team("Cruz Azul", CruzAzul, League.LigaMx);
            yield return new Team("Cruzeiro", Cruzeiro, League.LigadoBrasil);
            yield return new Team("Crystal Palace", CrystalPalace, League.NpowerChampionship);
            yield return new Team("C Funchal", CFunchal, League.LigaPortuguesa);
            yield return new Team("CS Sedan", CSSedan, League.Ligue2);
            yield return new Team("CSKA Moskva", CSKAMoskva, League.RussianLeague);
            yield return new Team("D.C. United", DCUnited, League.Mls);
            yield return new Team("Daegu FC", DaeguFC, League.KLeague);
            yield return new Team("Daejeon Citizen", DaejeonCitizen, League.KLeague);
            yield return new Team("Dagenham & Redbridge", DagenhamRedbridge, League.NpowerLeague2);
            yield return new Team("De Graafschap", DeGraafschap, League.Eredivisie);
            yield return new Team("Derby County", DerbyCounty, League.NpowerChampionship);
            yield return new Team("Derry City", DerryCity, League.AirtricityLeague);
            yield return new Team("Dijon Football", DijonFootball, League.Ligue2);
            yield return new Team("Dinamo Moskva", DinamoMoskva, League.RussianLeague);
            yield return new Team("Djurgardens IF", DjurgardensIF, League.Allsvenskan);
            yield return new Team("Doncaster Rovers", DoncasterRovers, League.NpowerLeague1);
            yield return new Team("Drogheda United", DroghedaUnited, League.AirtricityLeague);
            yield return new Team("Dundalk FC", DundalkFC, League.AirtricityLeague);
            yield return new Team("Dundee FC", DundeeFC, League.Spl);
            yield return new Team("Dundee United", DundeeUnited, League.Spl);
            yield return new Team("Dynamo Dresden", DynamoDresden, League.Bundesliga2);
            yield return new Team("Eintracht Braunschweig", EintrachtBraunschweig, League.Bundesliga2);
            yield return new Team("Eintracht Frankfurt", EintrachtFrankfurt, League.Bundesliga);
            yield return new Team("Elche CF", ElcheCF, League.LigaAdelante);
            yield return new Team("Empoli", Empoli, League.SerieB);
            yield return new Team("En Avant Guingamp", EnAvantGuingamp, League.Ligue2);
            yield return new Team("Energie Cottbus", EnergieCottbus, League.Bundesliga2);
            yield return new Team("Erzgebirge Aue", ErzgebirgeAue, League.Bundesliga2);
            yield return new Team("ES Troyes", ESTroyes, League.Ligue1);
            yield return new Team("Esbjerg", Esbjerg, League.Superliga);
            yield return new Team("Estoril", Estoril, League.LigaPortuguesa);
            yield return new Team("Estudiantes Tecos", EstudiantesTecos, League.LigaMx);
            yield return new Team("Everton", Everton, League.BarclaysPremierLeague);
            yield return new Team("Evian Thonon Gaillard FC", EvianThononGaillardFC, League.Ligue1);
            yield return new Team("Excelsior", Excelsior, League.Eredivisie);
            yield return new Team("Exeter City", ExeterCity, League.NpowerLeague2);
            yield return new Team("FC Augsburg", FCAugsburg, League.Bundesliga);
            yield return new Team("FC Barcelona B", FCBarcelonaB, League.LigaAdelante);
            yield return new Team("FC Barcelona", FCBarcelona, League.LigaBbva);
            yield return new Team("FC Basel", FCBasel, League.RaiffeisenSl);
            yield return new Team("FC Bayern", FCBayern, League.Bundesliga);
            yield return new Team("FC Cartagena", FCCartagena, League.LigaAdelante);
            yield return new Team("FC Copenhagen", FCCopenhagen, League.Superliga);
            yield return new Team("FC Dallas", FCDallas, League.Mls);
            yield return new Team("FC Groningen", FCGroningen, League.Eredivisie);
            yield return new Team("FC Ingolstadt 04", FCIngolstadt04, League.Bundesliga2);
            yield return new Team("FC Istres", FCIstres, League.Ligue2);
            yield return new Team("FC Krasnodar", FCKrasnodar, League.RussianLeague);
            yield return new Team("FC Lausanne-Sports", FCLausanneSports, League.RaiffeisenSl);
            yield return new Team("FC Lorient", FCLorient, League.Ligue1);
            yield return new Team("FC Luzern", FCLuzern, League.RaiffeisenSl);
            yield return new Team("FC Metz", FCMetz, League.Ligue2);
            yield return new Team("FC Midtjylland", FCMidtjylland, League.Superliga);
            yield return new Team("FC Nantes", FCNantes, League.Ligue2);
            yield return new Team("FC Nordsjlland", FCNordsjlland, League.Superliga);
            yield return new Team("FC Porto", FCPorto, League.LigaPortuguesa);
            yield return new Team("FC Rostov", FCRostov, League.RussianLeague);
            yield return new Team("FC Schalke 04", FCSchalke04, League.Bundesliga);
            yield return new Team("FC Seoul", FCSeoul, League.KLeague);
            yield return new Team("FC Sion", FCSion, League.RaiffeisenSl);
            yield return new Team("FC Sochaux", FCSochaux, League.Ligue1);
            yield return new Team("FC St. Gallen", FCStGallen, League.RaiffeisenSl);
            yield return new Team("FC St. Pauli", FCStPauli, League.Bundesliga2);
            yield return new Team("FC Thun", FCThun, League.RaiffeisenSl);
            yield return new Team("FC Twente", FCTwente, League.Eredivisie);
            yield return new Team("FC Utrecht", FCUtrecht, League.Eredivisie);
            yield return new Team("FC Volga Nizhniy Novgorod", FCVolgaNizhniyNovgorod, League.RussianLeague);
            yield return new Team("FC Zurich", FCZurich, League.RaiffeisenSl);
            yield return new Team("Feyenoord", Feyenoord, League.Eredivisie);
            yield return new Team("Figueirense", Figueirense, League.LigadoBrasil);
            yield return new Team("Fiorentina", Fiorentina, League.SerieA);
            yield return new Team("FK Haugesund", FKHaugesund, League.Tippeligaen);
            yield return new Team("Flamengo", Flamengo, League.LigadoBrasil);
            yield return new Team("Fleetwood Town", FleetwoodTown, League.NpowerLeague2);
            yield return new Team("Fluminense", Fluminense, League.LigadoBrasil);
            yield return new Team("Fortuna Dsseldorf", FortunaDsseldorf, League.Bundesliga);
            yield return new Team("Fredrikstad FK", FredrikstadFK, League.Tippeligaen);
            yield return new Team("FSV Frankfurt", FSVFrankfurt, League.Bundesliga2);
            yield return new Team("Fulham", Fulham, League.BarclaysPremierLeague);
            yield return new Team("GAIS", GAIS, League.Allsvenskan);
            yield return new Team("Galatasaray SK", GalatasaraySK, League.TurkLig);
            yield return new Team("Galway United", GalwayUnited, League.AirtricityLeague);
            yield return new Team("Gangwon FC", GangwonFC, League.KLeague);
            yield return new Team("Gazelec Ajaccio", GazelecAjaccio, League.Ligue2);
            yield return new Team("Gefle IF", GefleIF, League.Allsvenskan);
            yield return new Team("Genk", Genk, League.ProLeague);
            yield return new Team("Genoa", Genoa, League.SerieA);
            yield return new Team("Gent", Gent, League.ProLeague);
            yield return new Team("Getafe CF", GetafeCF, League.LigaBbva);
            yield return new Team("GIF Sundsvall", GIFSundsvall, League.Allsvenskan);
            yield return new Team("Gil Vicente FC", GilVicenteFC, League.LigaPortuguesa);
            yield return new Team("Gillingham", Gillingham, League.NpowerLeague2);
            yield return new Team("Girona FC", GironaFC, League.LigaAdelante);
            yield return new Team("Girondins Bordeaux", GirondinsBordeaux, League.Ligue1);
            yield return new Team("GKS Belchatow", GKSBelchatow, League.PolskaLiga);
            yield return new Team("Gliwice", Gliwice, League.PolskaLiga);
            yield return new Team("Gold Coast United", GoldCoastUnited, League.ALeague);
            yield return new Team("Gornik Zabrze", GornikZabrze, League.PolskaLiga);
            yield return new Team("Granada CF", GranadaCF, League.LigaBbva);
            yield return new Team("Grasshopper-Club", GrasshopperClub, League.RaiffeisenSl);
            yield return new Team("Gremio", Gremio, League.LigadoBrasil);
            yield return new Team("Grosseto", Grosseto, League.SerieB);
            yield return new Team("Guadalajara", Guadalajara, League.LigaMx);
            yield return new Team("GwangJu FC", GwangJuFC, League.KLeague);
            yield return new Team("GyeongNam FC", GyeongNamFC, League.KLeague);
            yield return new Team("Hajer", Hajer, League.SaudiProLeague);
            yield return new Team("Halmstads BK", HalmstadsBK, League.Allsvenskan);
            yield return new Team("Hamburger SV", HamburgerSV, League.Bundesliga);
            yield return new Team("Hannover 96", Hannover96, League.Bundesliga);
            yield return new Team("Hansa Rostock", HansaRostock, League.Bundesliga2);
            yield return new Team("Hartlepool United", HartlepoolUnited, League.NpowerLeague1);
            yield return new Team("Heart of Midlothian", HeartofMidlothian, League.Spl);
            yield return new Team("Helsingborgs IF", HelsingborgsIF, League.Allsvenskan);
            yield return new Team("Heracles Almelo", HeraclesAlmelo, League.Eredivisie);
            yield return new Team("Hercules CF", HerculesCF, League.LigaAdelante);
            yield return new Team("Hereford United", HerefordUnited, League.NpowerLeague2);
            yield return new Team("Hertha BSC", HerthaBSC, League.Bundesliga2);
            yield return new Team("Hibernian", Hibernian, League.Spl);
            yield return new Team("Honefoss BK", HonefossBK, League.Tippeligaen);
            yield return new Team("Houston Dynamo", HoustonDynamo, League.Mls);
            yield return new Team("Huddersfield Town", HuddersfieldTown, League.NpowerChampionship);
            yield return new Team("Hull City", HullCity, League.NpowerChampionship);
            yield return new Team("IF Elfsborg", IFElfsborg, League.Allsvenskan);
            yield return new Team("IFK Goteborg", IFKGoteborg, League.Allsvenskan);
            yield return new Team("IFK Norrkoping", IFKNorrkoping, League.Allsvenskan);
            yield return new Team("IK Start", IKStart, League.Tippeligaen);
            yield return new Team("Incheon United FC", IncheonUnitedFC, League.KLeague);
            yield return new Team("Inter", Inter, League.SerieA);
            yield return new Team("Internacional", Internacional, League.LigadoBrasil);
            yield return new Team("Inverness Caledonian Thistle", InvernessCaledonianThistle, League.Spl);
            yield return new Team("Ipswich Town", IpswichTown, League.NpowerChampionship);
            yield return new Team("Jagiellonia Bialystok", JagielloniaBialystok, League.PolskaLiga);
            yield return new Team("Jaguares de Chiapas", JaguaresdeChiapas, League.LigaMx);
            yield return new Team("Jeju United FC", JejuUnitedFC, League.KLeague);
            yield return new Team("Jeonbuk Hyundai Motors", JeonbukHyundaiMotors, League.KLeague);
            yield return new Team("Juve Stabia", JuveStabia, League.SerieB);
            yield return new Team("Juventus", Juventus, League.SerieA);
            yield return new Team("Kaizer Chiefs", KaizerChiefs, League.SouthAfricanFl);
            yield return new Team("Kalmar FF", KalmarFF, League.Allsvenskan);
            yield return new Team("Kapfenberger SV", KapfenbergerSV, League.Abundesliga);
            yield return new Team("Karlsruher SC", KarlsruherSC, League.Bundesliga2);
            yield return new Team("Kilmarnock", Kilmarnock, League.Spl);
            yield return new Team("Korona Kielce", KoronaKielce, League.PolskaLiga);
            yield return new Team("Kortrijk", Kortrijk, League.ProLeague);
            yield return new Team("Krylya Sovetov Samara", KrylyaSovetovSamara, League.RussianLeague);
            yield return new Team("Kuban Krasnodar", KubanKrasnodar, League.RussianLeague);
            yield return new Team("La Spezia", LaSpezia, League.SerieB);
            yield return new Team("Lanciano", Lanciano, League.SerieB);
            yield return new Team("Lazio", Lazio, League.SerieA);
            yield return new Team("LB Chateauroux", LBChateauroux, League.Ligue2);
            yield return new Team("Le Havre AC", LeHavreAC, League.Ligue2);
            yield return new Team("Le Mans FC", LeMansFC, League.Ligue2);
            yield return new Team("Lecce", Lecce, League.SerieB);
            yield return new Team("Lech Poznan", LechPoznan, League.PolskaLiga);
            yield return new Team("Lechia Gdansk", LechiaGdansk, League.PolskaLiga);
            yield return new Team("Leeds United", LeedsUnited, League.NpowerChampionship);
            yield return new Team("Legia Warszawa", LegiaWarszawa, League.PolskaLiga);
            yield return new Team("Leicester City", LeicesterCity, League.NpowerChampionship);
            yield return new Team("Levante UD", LevanteUD, League.LigaBbva);
            yield return new Team("Leyton Orient", LeytonOrient, League.NpowerLeague1);
            yield return new Team("Lierse", Lierse, League.ProLeague);
            yield return new Team("Lillestrom SK", LillestromSK, League.Tippeligaen);
            yield return new Team("Liverpool", Liverpool, League.BarclaysPremierLeague);
            yield return new Team("Livorno", Livorno, League.SerieB);
            yield return new Team("LKS Lodz", LKSLodz, League.PolskaLiga);
            yield return new Team("Lokeren", Lokeren, League.ProLeague);
            yield return new Team("Lokomotiv Moskva", LokomotivMoskva, League.RussianLeague);
            yield return new Team("Los Angeles Galaxy", LosAngelesGalaxy, League.Mls);
            yield return new Team("LOSC Lille", LOSCLille, League.Ligue1);
            yield return new Team("Macclesfield Town", MacclesfieldTown, League.NpowerLeague2);
            yield return new Team("Malaga CF", MalagaCF, League.LigaBbva);
            yield return new Team("Malmo FF", MalmoFF, League.Allsvenskan);
            yield return new Team("Manchester City", ManchesterCity, League.BarclaysPremierLeague);
            yield return new Team("Manchester United", ManchesterUnited, League.BarclaysPremierLeague);
            yield return new Team("Mechelen", Mechelen, League.ProLeague);
            yield return new Team("Melbourne Heart", MelbourneHeart, League.ALeague);
            yield return new Team("Melbourne Victory", MelbourneVictory, League.ALeague);
            yield return new Team("Middlesbrough", Middlesbrough, League.NpowerChampionship);
            yield return new Team("Milan", Milan, League.SerieA);
            yield return new Team("Millwall", Millwall, League.NpowerChampionship);
            yield return new Team("Milton Keynes Dons", MiltonKeynesDons, League.NpowerLeague1);
            yield return new Team("Mjallby AIF", MjallbyAIF, League.Allsvenskan);
            yield return new Team("Modena", Modena, League.SerieB);
            yield return new Team("Molde FK", MoldeFK, League.Tippeligaen);
            yield return new Team("Monarcas Morelia", MonarcasMorelia, League.LigaMx);
            yield return new Team("Monterrey", Monterrey, League.LigaMx);
            yield return new Team("Montpellier SC", MontpellierSC, League.Ligue1);
            yield return new Team("Montreal Impact", MontrealImpact, League.Mls);
            yield return new Team("Mordov. Saransk", MordovSaransk, League.RussianLeague);
            yield return new Team("Morecambe", Morecambe, League.NpowerLeague2);
            yield return new Team("Moreira Conegos", MoreiraConegos, League.LigaPortuguesa);
            yield return new Team("Motherwell", Motherwell, League.Spl);
            yield return new Team("MSV Duisburg", MSVDuisburg, League.Bundesliga2);
            yield return new Team("N. Recife", NRecife, League.LigadoBrasil);
            yield return new Team("NAC Breda", NACBreda, League.Eredivisie);
            yield return new Team("Najran", Najran, League.SaudiProLeague);
            yield return new Team("Napoli", Napoli, League.SerieA);
            yield return new Team("Nastic de Tarragona", NasticdeTarragona, League.LigaAdelante);
            yield return new Team("NEC", NEC, League.Eredivisie);
            yield return new Team("Neuchatel Xamax", NeuchatelXamax, League.RaiffeisenSl);
            yield return new Team("New England Revolution", NewEnglandRevolution, League.Mls);
            yield return new Team("New York Red Bulls", NewYorkRedBulls, League.Mls);
            yield return new Team("Newcastle United Jets", NewcastleUnitedJets, League.ALeague);
            yield return new Team("Newcastle United", NewcastleUnited, League.BarclaysPremierLeague);
            yield return new Team("Nimes Olympique", NimesOlympique, League.Ligue2);
            yield return new Team("Northampton Town", NorthamptonTown, League.NpowerLeague2);
            yield return new Team("Norwich City", NorwichCity, League.BarclaysPremierLeague);
            yield return new Team("Nottingham Forest", NottinghamForest, League.NpowerChampionship);
            yield return new Team("Notts County", NottsCounty, League.NpowerLeague1);
            yield return new Team("Novara", Novara, League.SerieB);
            yield return new Team("Odd Grenland", OddGrenland, League.Tippeligaen);
            yield return new Team("Odense BK", OdenseBK, League.Superliga);
            yield return new Team("OGC Nice", OGCNice, League.Ligue1);
            yield return new Team("Oldham Athletic", OldhamAthletic, League.NpowerLeague1);
            yield return new Team("Olympiakos", Olympiakos, League.HellasLiga);
            yield return new Team("Olympique de Marseille", OlympiquedeMarseille, League.Ligue1);
            yield return new Team("Olympique Lyonnais", OlympiqueLyonnais, League.Ligue1);
            yield return new Team("Orebro SK", OrebroSK, League.Allsvenskan);
            yield return new Team("Orlando Pirates", OrlandoPirates, League.SouthAfricanFl);
            yield return new Team("Oud-Heverlee Leuven", OudHeverleeLeuven, League.ProLeague);
            yield return new Team("Oxford United", OxfordUnited, League.NpowerLeague2);
            yield return new Team("P. Campinas", PCampinas, League.LigadoBrasil);
            yield return new Team("Pachuca", Pachuca, League.LigaMx);
            yield return new Team("Pacos Ferreira", PacosFerreira, League.LigaPortuguesa);
            yield return new Team("Padova", Padova, League.SerieB);
            yield return new Team("Palermo", Palermo, League.SerieA);
            yield return new Team("Palmeiras", Palmeiras, League.LigadoBrasil);
            yield return new Team("Panathinaikos", Panathinaikos, League.HellasLiga);
            yield return new Team("PAOK", PAOK, League.HellasLiga);
            yield return new Team("Paris Saint-Germain", ParisSaintGermain, League.Ligue1);
            yield return new Team("Parma", Parma, League.SerieA);
            yield return new Team("PEC Zwolle", PECZwolle, League.Eredivisie);
            yield return new Team("Perth Glory", PerthGlory, League.ALeague);
            yield return new Team("Pescara", Pescara, League.SerieA);
            yield return new Team("Peterborough United", PeterboroughUnited, League.NpowerChampionship);
            yield return new Team("Philadelphia Union", PhiladelphiaUnion, League.Mls);
            yield return new Team("Plymouth Argyle", PlymouthArgyle, League.NpowerLeague2);
            yield return new Team("Podbeskidzie Bielsko-Biala", PodbeskidzieBielskoBiala, League.PolskaLiga);
            yield return new Team("Pohang Steelers", PohangSteelers, League.KLeague);
            yield return new Team("Polonia Warszawa", PoloniaWarszawa, League.PolskaLiga);
            yield return new Team("Port Vale", PortVale, League.NpowerLeague2);
            yield return new Team("Portland Timbers", PortlandTimbers, League.Mls);
            yield return new Team("Portsmouth", Portsmouth, League.NpowerLeague1);
            yield return new Team("Portuguesa", Portuguesa, League.LigadoBrasil);
            yield return new Team("Preston North End", PrestonNorthEnd, League.NpowerLeague1);
            yield return new Team("PSV", PSV, League.Eredivisie);
            yield return new Team("Puebla", Puebla, League.LigaMx);
            yield return new Team("Queens Park Rangers", QueensParkRangers, League.BarclaysPremierLeague);
            yield return new Team("Queretaro", Queretaro, League.LigaMx);
            yield return new Team("Racing Club de Lens", RacingClubdeLens, League.Ligue2);
            yield return new Team("Racing de Santander", RacingdeSantander, League.LigaAdelante);
            yield return new Team("Randers FC", RandersFC, League.Superliga);
            yield return new Team("Rapid Wien", RapidWien, League.Abundesliga);
            yield return new Team("Rayo Vallecano", RayoVallecano, League.LigaBbva);
            yield return new Team("RC Celta de Vigo", RCCeltadeVigo, League.LigaBbva);
            yield return new Team("RC Deportivo", RCDeportivo, League.LigaBbva);
            yield return new Team("RC Recreativo", RCRecreativo, League.LigaAdelante);
            yield return new Team("RCD Espanyol", RCDEspanyol, League.LigaBbva);
            yield return new Team("RCD Mallorca", RCDMallorca, League.LigaBbva);
            yield return new Team("Reading", Reading, League.BarclaysPremierLeague);
            yield return new Team("Real Betis Balompie", RealBetisBalompie, League.LigaBbva);
            yield return new Team("Real Madrid", RealMadrid, League.LigaBbva);
            yield return new Team("Real Murcia CF", RealMurciaCF, League.LigaAdelante);
            yield return new Team("Real Salt Lake", RealSaltLake, League.Mls);
            yield return new Team("Real Sociedad", RealSociedad, League.LigaBbva);
            yield return new Team("Real Sporting de Gijon", RealSportingdeGijon, League.LigaAdelante);
            yield return new Team("Real Valladolid", RealValladolid, League.LigaBbva);
            yield return new Team("Real Zaragoza", RealZaragoza, League.LigaBbva);
            yield return new Team("Red Bull Salzburg", RedBullSalzburg, League.Abundesliga);
            yield return new Team("Reggina", Reggina, League.SerieB);
            yield return new Team("Rio Ave FC", RioAveFC, League.LigaPortuguesa);
            yield return new Team("RKC Waalwijk", RKCWaalwijk, League.Eredivisie);
            yield return new Team("RM Castilla", RMCastilla, League.LigaAdelante);
            yield return new Team("Rochdale", Rochdale, League.NpowerLeague2);
            yield return new Team("Roda JC Kerkrade", RodaJCKerkrade, League.Eredivisie);
            yield return new Team("Roma", Roma, League.SerieA);
            yield return new Team("Rosenborg BK", RosenborgBK, League.Tippeligaen);
            yield return new Team("Ross County", RossCounty, League.Spl);
            yield return new Team("Rotherham United", RotherhamUnited, League.NpowerLeague2);
            yield return new Team("Rubin Kazan", RubinKazan, League.RussianLeague);
            yield return new Team("Ruch Chorzow", RuchChorzow, League.PolskaLiga);
            yield return new Team("S. Recife", SRecife, League.LigadoBrasil);
            yield return new Team("Sampdoria", Sampdoria, League.SerieA);
            yield return new Team("San Jose Earthquakes", SanJoseEarthquakes, League.Mls);
            yield return new Team("San Luis", SanLuis, League.LigaMx);
            yield return new Team("Sandnes Ulf", SandnesUlf, League.Tippeligaen);
            yield return new Team("Sangju Sangmu Phoenix FC", SangjuSangmuPhoenixFC, League.KLeague);
            yield return new Team("Santos Laguna", SantosLaguna, League.LigaMx);
            yield return new Team("Santos", Santos, League.LigadoBrasil);
            yield return new Team("Sao Paulo", SaoPaulo, League.LigadoBrasil);
            yield return new Team("Sassuolo", Sassuolo, League.SerieB);
            yield return new Team("SC Bastia", SCBastia, League.Ligue1);
            yield return new Team("SC Beira-Mar", SCBeiraMar, League.LigaPortuguesa);
            yield return new Team("SC Braga", SCBraga, League.LigaPortuguesa);
            yield return new Team("SC Freiburg", SCFreiburg, League.Bundesliga);
            yield return new Team("SC Heerenveen", SCHeerenveen, League.Eredivisie);
            yield return new Team("SC Olhanense", SCOlhanense, League.LigaPortuguesa);
            yield return new Team("SC Paderborn", SCPaderborn, League.Bundesliga2);
            yield return new Team("SC Wiener Neustadt", SCWienerNeustadt, League.Abundesliga);
            yield return new Team("Scunthorpe United", ScunthorpeUnited, League.NpowerLeague1);
            yield return new Team("SD Huesca", SDHuesca, League.LigaAdelante);
            yield return new Team("SD Ponferradina", SDPonferradina, League.LigaAdelante);
            yield return new Team("Seattle Sounders", SeattleSounders, League.Mls);
            yield return new Team("Seongnam Ilhwa Chunma", SeongnamIlhwaChunma, League.KLeague);
            yield return new Team("Servette FC", ServetteFC, League.RaiffeisenSl);
            yield return new Team("Sevilla FC", SevillaFC, League.LigaBbva);
            yield return new Team("Shamrock Rovers", ShamrockRovers, League.AirtricityLeague);
            yield return new Team("Sheffield United", SheffieldUnited, League.NpowerLeague1);
            yield return new Team("Sheffield Wednesday", SheffieldWednesday, League.NpowerChampionship);
            yield return new Team("Shelbourne", Shelbourne, League.AirtricityLeague);
            yield return new Team("Shrewsbury Town", ShrewsburyTown, League.NpowerLeague1);
            yield return new Team("Siena", Siena, League.SerieA);
            yield return new Team("Silkeborg IF", SilkeborgIF, League.Superliga);
            yield return new Team("SK Brann", SKBrann, League.Tippeligaen);
            yield return new Team("SL Benfica", SLBenfica, League.LigaPortuguesa);
            yield return new Team("Slask Wroclaw", SlaskWroclaw, League.PolskaLiga);
            yield return new Team("Sligo Rovers", SligoRovers, League.AirtricityLeague);
            yield return new Team("SM Caen", SMCaen, League.Ligue2);
            yield return new Team("Snderjyske", Snderjyske, League.Superliga);
            yield return new Team("Sogndal Fotball", SogndalFotball, League.Tippeligaen);
            yield return new Team("Southampton", Southampton, League.BarclaysPremierLeague);
            yield return new Team("Southend United", SouthendUnited, League.NpowerLeague2);
            yield return new Team("Spartak Moskva", SpartakMoskva, League.RussianLeague);
            yield return new Team("Spartak Nalchik", SpartakNalchik, League.RussianLeague);
            yield return new Team("Sporting CP", SportingCP, League.LigaPortuguesa);
            yield return new Team("Sporting KC", SportingKC, League.Mls);
            yield return new Team("SPVGG Greuther Frth", SPVGGGreutherFrth, League.Bundesliga);
            yield return new Team("SSV Jahn", SSVJahn, League.Bundesliga2);
            yield return new Team("St. Johnstone", StJohnstone, League.Spl);
            yield return new Team("St. Mirren", StMirren, League.Spl);
            yield return new Team("St. Patrick's Athletic", StPatricksAthletic, League.AirtricityLeague);
            yield return new Team("Stabaek Fotball", StabaekFotball, League.Tippeligaen);
            yield return new Team("Stade Brestois", StadeBrestois, League.Ligue1);
            yield return new Team("Stade de Reims", StadedeReims, League.Ligue1);
            yield return new Team("Stade Lavallois", StadeLavallois, League.Ligue2);
            yield return new Team("Stade Rennais", StadeRennais, League.Ligue1);
            yield return new Team("Standard", Standard, League.ProLeague);
            yield return new Team("Stevenage", Stevenage, League.NpowerLeague1);
            yield return new Team("Stoke City", StokeCity, League.BarclaysPremierLeague);
            yield return new Team("Stromsgodset Toppfotball", StromsgodsetToppfotball, League.Tippeligaen);
            yield return new Team("Sturm Graz", SturmGraz, League.Abundesliga);
            yield return new Team("Sunderland", Sunderland, League.BarclaysPremierLeague);
            yield return new Team("Suwon Samsung Bluewings", SuwonSamsungBluewings, League.KLeague);
            yield return new Team("SV Mattersburg", SVMattersburg, League.Abundesliga);
            yield return new Team("SV Ried", SVRied, League.Abundesliga);
            yield return new Team("SV Sandhausen", SVSandhausen, League.Bundesliga2);
            yield return new Team("Swansea City", SwanseaCity, League.BarclaysPremierLeague);
            yield return new Team("Swindon Town", SwindonTown, League.NpowerLeague1);
            yield return new Team("Sydney FC", SydneyFC, League.ALeague);
            yield return new Team("Syrianska FC", SyrianskaFC, League.Allsvenskan);
            yield return new Team("Szczecin", Szczecin, League.PolskaLiga);
            yield return new Team("Terek Grozny", TerekGrozny, League.RussianLeague);
            yield return new Team("Terni", Terni, League.SerieB);
            yield return new Team("Tigres U.A.N.L.", TigresUANL, League.LigaMx);
            yield return new Team("Toluca", Toluca, League.LigaMx);
            yield return new Team("Tom Tomsk", TomTomsk, League.RussianLeague);
            yield return new Team("Torino", Torino, League.SerieA);
            yield return new Team("Toronto FC", TorontoFC, League.Mls);
            yield return new Team("Torquay United", TorquayUnited, League.NpowerLeague2);
            yield return new Team("Tottenham Hotspur", TottenhamHotspur, League.BarclaysPremierLeague);
            yield return new Team("Toulouse FC", ToulouseFC, League.Ligue1);
            yield return new Team("Tours FC", ToursFC, League.Ligue2);
            yield return new Team("Tranmere Rovers", TranmereRovers, League.NpowerLeague1);
            yield return new Team("Tromso IL", TromsoIL, League.Tippeligaen);
            yield return new Team("TSV 1860 Munchen", TSV1860Munchen, League.Bundesliga2);
            yield return new Team("U.C.D.", UCD, League.AirtricityLeague);
            yield return new Team("U.N.A.M.", UNAM, League.LigaMx);
            yield return new Team("UD Almeria", UDAlmeria, League.LigaAdelante);
            yield return new Team("UD Las Palmas", UDLasPalmas, League.LigaAdelante);
            yield return new Team("Udinese", Udinese, League.SerieA);
            yield return new Team("Ulsan Hyundai FC", UlsanHyundaiFC, League.KLeague);
            yield return new Team("Uniao Desportiva de Leiria", UniaoDesportivadeLeiria, League.LigaPortuguesa);
            yield return new Team("US Boulogne", USBoulogne, League.Ligue2);
            yield return new Team("Valencia CF", ValenciaCF, League.LigaBbva);
            yield return new Team("Valenciennes FC", ValenciennesFC, League.Ligue1);
            yield return new Team("Valerenga Fotball", ValerengaFotball, League.Tippeligaen);
            yield return new Team("Vancouver Whitecaps", VancouverWhitecaps, League.Mls);
            yield return new Team("Varese", Varese, League.SerieB);
            yield return new Team("Vasco da Gama", VascodaGama, League.LigadoBrasil);
            yield return new Team("Vercelli", Vercelli, League.SerieB);
            yield return new Team("Verona", Verona, League.SerieB);
            yield return new Team("VfB Stuttgart", VfBStuttgart, League.Bundesliga);
            yield return new Team("VfL Bochum", VfLBochum, League.Bundesliga2);
            yield return new Team("VfL Wolfsburg", VfLWolfsburg, League.Bundesliga);
            yield return new Team("VfR Aalen", VfRAalen, League.Bundesliga2);
            yield return new Team("Vicenza", Vicenza, League.SerieB);
            yield return new Team("Viking FK", VikingFK, League.Tippeligaen);
            yield return new Team("Villarreal B", VillarrealB, League.LigaAdelante);
            yield return new Team("Villarreal CF", VillarrealCF, League.LigaAdelante);
            yield return new Team("Vitesse", Vitesse, League.Eredivisie);
            yield return new Team("Vitoria Guimaraes", VitoriaGuimaraes, League.LigaPortuguesa);
            yield return new Team("Vitoria FC", VitoriaSetubal, League.LigaPortuguesa);
            yield return new Team("VVV-Venlo", VVVVenlo, League.Eredivisie);
            yield return new Team("Waasland-Beveren", WaaslandBeveren, League.ProLeague);
            yield return new Team("Wacker Innsbruck", WackerInnsbruck, League.Abundesliga);
            yield return new Team("Walsall", Walsall, League.NpowerLeague1);
            yield return new Team("Wanderers FC", WanderersFC, League.ALeague);
            yield return new Team("Waregem", Waregem, League.ProLeague);
            yield return new Team("Watford", Watford, League.NpowerChampionship);
            yield return new Team("Wellington Phoenix", WellingtonPhoenix, League.ALeague);
            yield return new Team("Werder Bremen", WerderBremen, League.Bundesliga);
            yield return new Team("West Bromwich Albion", WestBromwichAlbion, League.BarclaysPremierLeague);
            yield return new Team("West Ham United", WestHamUnited, League.BarclaysPremierLeague);
            yield return new Team("Widzew Lodz", WidzewLodz, League.PolskaLiga);
            yield return new Team("Wigan Athletic", WiganAthletic, League.BarclaysPremierLeague);
            yield return new Team("Willem II", WillemII, League.Eredivisie);
            yield return new Team("Wisla Krakow", WislaKrakow, League.PolskaLiga);
            yield return new Team("Wolfsberger AC", WolfsbergerAC, League.Abundesliga);
            yield return new Team("Wolverhampton Wanderers", WolverhamptonWanderers, League.NpowerChampionship);
            yield return new Team("Wycombe Wanderers", WycombeWanderers, League.NpowerLeague2);
            yield return new Team("Xerez CD", XerezCD, League.LigaAdelante);
            yield return new Team("Xoloitzcuintles de Tijuana", XoloitzcuintlesdeTijuana, League.LigaMx);
            yield return new Team("Yeovil Town", YeovilTown, League.NpowerLeague1);
            yield return new Team("York City", YorkCity, League.NpowerLeague2);
            yield return new Team("Zaglebie Lubin", ZaglebieLubin, League.PolskaLiga);
            yield return new Team("Zenit St. Petersburg", ZenitStPetersburg, League.RussianLeague);
        }
    }
}